**PYTHON** - Practice Subjective

**Q1.** Write a Python program to get the string from the given string where all the occurrence of its first char has been changed to "$," except first char itself? <br>
**Sample String:** 'prospect' <br>
Expected Result : 'pros$ect'

**Q2.** Write a Python program to get the single string from the two given strings, and separated by the space and swap the first two characters of each string? <br>
**Sample String :** 'abc', 'xyz'. <br>
**Expected Result:** 'xyc abz'

**Q3.** Write the Python program to add 'ing' at the end of the given string (length of the string should be at least 3). If given string already ends with 'ing,' then add 'ly' instead. If string length of the given string is less than 3, leave it unchanged? <br>
**Sample string:** ' abc ' <br>
**Expected result:** ' abcing ' <br>
**Sample string:** ' string ' <br>
**Expected result:** ' stringly '

**Q4.** Write the Python program to find the first appearance of the substring 'not' and 'poor' from the given string, if 'not' follows the 'poor', replace the whole 'not'...' poor' substring with 'good'.Return the resulting string. <br>
**Sample string:** 'The lyrics are not that poor!' 'The lyrics are poor!' <br>
**Expected Result:** 'The lyrics are good!' 'The lyrics are poor!'

**Q5.** Write the Python program to remove the characters which have odd index values of a given string.

**Q6.** Write the Python function to get a string made of 4 copies of the last two characters of the specified string (length must be at least 2). <br>
**Sample function and result :** <br>
insert-end ('Python') -> abababab <br>
insert-end('Exercises') -> jkjkjkjk

**Q7.** Write the python function to get a string made of its first three characters of a specified string. If the length of the string is less than 3 then return the original string. <br>
**Sample function and result :** <br>
first-three('ipy') -> ipy <br>
first-three('python') -> pyt

**Q8.** Write the python program to print the following floating numbers up to 2 decimal places?

**Q9.** Write the Python program to format a number with a percentage?

**Q10.** Write the Python program to count occurrences of a substring in a String?

**Q11.** Write the Python program to count repeated characters in a string. <br>
**Sample string:** ' thequickbrownjumpsoverthelazydog ' <br>
**Expected output:** <br>
o 3 <br>
e 3 <br>
u 2 <br>
h 2 <br>
r 2 <br>
t 2

**Q12.** Write the Python program to print the square and cube symbol in the area of a rectangle and volume of a cylinder? <br>
**Sample output:** <br> The area of the rectangle is 1256.66cm2 <br>
The volume of the cylinder is 1254.725cm3

**Q13.** Write the Python program to check if a string contains all letters of the alphabet?

**Q14.** Write the Python program to find the second most repeated word in a given string?

**Q15.** Write the Python program to find the minimum window in the given string, which will contains all the characters of another given strings? <br>
**Example 1** <br>
Input : string1 = " PRWSOERIUSFK " <br>
string2 = " OSU " <br>
Output: Minimum window is "OERIUS"

**Q16.** Write the Python program to find smallest window that contains all characters of the given string? <br>
**Original Strings:**
asdaewsqgtwwsa <br>
**Smallest window that contains all characters of the said string:**
Daewsqgt

**Q17.** Write the Python program to count number of substrings from a given string of lowercase alphabets with exactly k distinct (given) characters? <br>
**Input a string (lowercase alphabets):** wolf <br>
**Input k:** 4 <br>
**Number of substrings with exactly 4 distinct characters:** 1

**Q18.** Write the Python program to count number of non-empty substrings of the given string? <br>
Input a string: w3resource <br>
Number of substrings: <br>
55

**Q19.** Write the Python program to count number of substrings with same first and last characters of the given string? <br>
**Input a string:** abcd <br>
4

**Q20.** Write the Python program to count the number of strings where the string length is 2 or more, and first and last character are same from a given list of strings. <br>
**Sample List:** ['abc', 'xyz', 'wxw', '1331'] <br>
**Expected Result:** 2

**Q21.** Write the Python program to get a list, sorted in increasing order by the last element in each tuple from the given list of non-empty tuples? <br>
**Sample List-** [ (2, 5), (1, 2), (4, 4), (2, 3), (2, 1) ]
**Expected Result-** [ (2, 1), (1, 2), (2, 3), (4, 4), (2, 5) ]

**Q22.** Write the Python program to remove duplicates from a list?

**Q23.** Write the Python program to find the list of words that are longer than n from a given list of words?

**Q24.** Write the Python program to print a specified list after removing the 0th, 4th, and 5th elements? <br>
**Sample List-** ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow'] <br>
**Expected Output-** ['Green', 'White', 'Black']

**Q25.** Write the Python program to generate all permutations of a list in Python?

**Q26.** Write the Python program to convert a pair of values into a sorted unique array? <br>
**Original List-** [ (1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ] <br>
**Sorted Unique Data-** [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

**Q27.** Write the Python class to convert an integer to a roman numeral?

**Q28.** Write the Python class to convert a Roman numeral to an integer?

**Q29.** Write the Python class to find the validity of the string of the parentheses, '(', ')', '{', '}', '[' and '] and the brackets must be closed in the correct order, example - "()" and "()[]{}" are valid but "[)", "({[)]" and "{{{" are invalid.

**Q30.** Write the Python class to get all possible unique subsets from a set of distinct integers? <br>
**Input-** [4, 5, 6] <br>
**Output-** [[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]

Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number? <br>
**Input:** numbers- [10,20,10,40,50,60,70], target=50 <br>
**Output-** 3, 4

Q32. Write the Python class to find the three elements that sum to zero from the set of n real numbers? <br>
**Input array-** [-25, -10, -7, -3, 2, 4, 8, 10] <br>
**Output-** [[-10, 2, 8], [-7, -3, 10]]

**Q33.** Write the Python class to implement pow(x, n)?

**Q34.** Write the Python class which has two methods get_String and print_String. get_String accept the string from the user and print_String print the string in upper case.

**Q35.** Write the Python class named Rectangle constructed by a and width and the method which will compute the area of the rectangle?

**Q36.** Write the Python class named Circle constructed by the radius and two methods which will compute the area and perimeter of the circle?

**Q37.** Write the Python program to get the class name of an instance in Python?

**Q38.** Write the Python program to count the number of students of individual class? <br>
**Sample data classes** = ( ('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1),)<br>
**Expected Output:** Counter({'VI': 3, 'V': 2, 'VII': 1})

**Q39.** Write the Python program to create an instance of an OrderedDict using the given dictionary and sort dictionary during the creation and print members of the dictionary in reverse order?<br>
**Expected Output:** <br>
Angola 244. <br>
Andorra 376.<br>
Algeria 213.<br>
Afghanistan 93.<br>
Albania 355.<br>
**In reverse order:**<br>
Albania 355.<br>
Afghanistan 93. <br>
Algeria 213. <br>
Andorra 376.<br>
Angola 244.

**Q40.** Write the Python program to compare two unordered lists (not sets)?<br>
**Expected Output:** False

**Q41.** Write the Python program to get an array buffer information? <br>
**Expected Output:** Array buffer start address in memory and number of elements. <br>
(25855056, 2)

**Q42.** Write the Python program to convert an array to an array of machine values and return the bytes representation? <br>
Expected Output: Original arrayA1: array('i', [1, 2, 3, 4, 5, 6]) <br>
Array of bytes: <br>
b'010000000200000003000000040000000500000006000000' 

**Q43.** Write the Python program to read a string and interpreting the string as an array of machine values? <br>
**Expected Output:** array1- array('i', [7, 8, 9, 10]) <br>
Bytes- b'0700000008000000090000000a000000' <br>
array2- array('i', [7, 8, 9, 10]) <br>

**Q44.** Write the Python program to push three items into the heap and return the smallest item from the heap. Also, return and pop the smallest item from the heap? <br>
**Expected Output:** Items in the heap- ('VI', 1). ('VII', 3). ('VIII', 2). <br>
The smallest item in the heap: <br>
('VI', 1).<br>
Pop the smallest item in the heap:<br>
('VII', 2).<br>
('VIII', 3).

**Q45.** Write the Python program to locate the left insertion point for a specified value in sorted order? <br>
**Expected Output:** <br>
4 2

**Q46.** Write the Python program to create the FIFO queue? <br>
**Expected Output:** <br>
0 1 2 3

**Q47.** Write the Python program to calculate the harmonic sum of n-1. <br>
**Note:** The harmonic sum is the sum of reciprocals of the positive Integers? <br>
Example -

**Q48.** Write the NumPy program to create a 2d array with 6 on the border and 0 inside? <br>
**Expected Output :** Original array- <br>
[ [6 6 6 6 6] <br>
[ 6 6 6 6 6] <br>
[ 6 6 6 6 6 ] <br>
[ 6 6 6 6 6 ] <br>
[ 6 6 6 6 ] ]. <br>
6 on the border and 0 inside in the array-
[[ 6 6 6 6 6] <br>
[ 6 0 0 0 6] <br>
[ 6 0 0 0 6]<br>
[ 6 0 0 0 6]<br>
[ 6 6 6 6 6]]

**Q49.** Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern? <br>
Checkerboard pattern- <br>
[[3 9 3 9 3 9 3 9] <br>
[9 3 9 3 9 3 9 3]<br>
[3 9 3 9 3 9 3 9]<br>
[9 3 9 3 9 3 9 3]<br>
[3 9 3 9 3 9 3 9]<br>
[9 3 9 3 9 3 9 3]<br>
[3 9 3 9 3 9 3 9]<br>
[9 3 9 3 9 3 9 3]].<br>

**Q50.** Write the NumPy program to create an empty and a full array. <br>
Expected Output- <br>
[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306] <br>
[1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]<br>
[8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]<br>
[[6 6 6]<br>
[6 6 6]<br>
[6 6 6]]

**Q51.** Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array. <br>
**Sample Array-** [0, 12, 45.21 ,34, 99.91] <br>
**Expected Output:** Values in Fahrenheit degrees- <br>
[ 0. 12. 45.21 34. 99.91] <br>
Values in Centigrade degrees- <br>
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

**Q52.** Write the NumPy program to find the real and imaginary parts of an array of complex numbers? <br>
**Expected Output:** Original array [ 1.00000000+0.j 0.70710678+0.70710678j] <br>
Real part of the array-<br>
[ 1. 0.70710678]<br>
Imaginary part of the array- <br>
[ 0. 0.70710678]

**Q53.** Write the NumPy program to test whether each element of a 1-D array is also present in the second array? <br>
**Expected Output:** Array1: [ 0 10 20 40 60] <br>
Array2: [0, 40] <br>
Compare each element of array1 and array2 <br>
[ True False False True False]

**Q54.** Write the NumPy program to find common values between two arrays? <br>
**Expected Output:** Array1: [ 0 10 20 40 60] <br>
Array2: [10, 30, 40] <br>
Common values between two arrays- <br>
[10 40]

**Q55.** Write the NumPy program to get the unique elements of an array? <br>
**Expected Output:** Original array- <br>
[10 10 20 20 30 30] <br>
Unique elements of the above array- <br>
[10 20 30] <br>
Original array- <br>
[[1 1] <br>
[2 3]] <br>
Unique elements of the above array- <br>
[1 2 3] 

**Q56.** Write the NumPy program to find the set exclusive-or of two arrays. <br>
Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays? <br>
Array1- [ 0 10 20 40 60 80] <br>
Array2- [10, 30, 40, 50, 70] <br>
Unique values that are in only one (not both) of the input arrays- <br>
[ 0 20 30 50 60 70 80] 

**Q57.** Write the NumPy program to test if all elements in an array evaluate to True ? <br>
Note: 0 evaluates to False in NumPy.

**Q58.** Write the NumPy program to test whether any array element along the given axis evaluates to True? <br>
**Note:** 0 evaluates to False in NumPy.

**Q59.** Write the NumPy program to construct an array by repeating? <br>
Sample array- [1, 2, 3, 4] <br>
**Expected Output:** Original array <br>
[1, 2, 3, 4] <br>
Repeating 2 times <br>
[1 2 3 4 1 2 3 4] <br>
Repeating 3 times <br>
[1 2 3 4 1 2 3 4 1 2 3 4]

**Q60.** Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array? <br>
Original array- [1 2 3 4 5 6] <br>
Maximum Values- 5 <br>
Minimum Values- 0

**Q61.** Write the NumPy program compare two arrays using numpy? <br>
Array a- [1 2] <br>
Array b- [4 5] <br>
a > b <br>
[False False] <br>
a >= b
[False False] <br>
a < b <br>
[ True True] <br>
a <= b <br>
[ True True]

**Q62.** Write the NumPy program to sort an along the first, last axis of an array? <br>
Sample array- [[2,5],[4,4]] <br>
**Expected Output:** Original array: <br>
[[4 6] <br>
[2 1]] <br>
Sort along the first axis: <br>
[[2 1] <br>
[4 6]] <br>
Sort along the last axis- <br>
[[1 2] <br>
[4 6]]

**Q63.** Write the NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name). <br>
first_names - ( Betsey, Shelley, Lanell, Genesis, Margery ) <br>
last_names - ( Battle, Brien, Plotner, Stahl, Woolum ) <br>
**Expected Output-** <br>
[1 3 2 4 0]

**Q64.** Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array? <br>
Original array- <br>
[[ 0 10 20] <br>
[20 30 40]] <br>
Values bigger than 10 = [20 20 30 40] <br>
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

**Q65.** Write the NumPy program to find the memory size of a NumPy array? <br>
**Expected Output-** 128 bytes

**Q66.** Write the NumPy program to create an array of ones and an array of zeros? <br>
**Expected Output:** Create an array of zeros <br>
Default type is float <br>
[[ 0. 0.]] <br>
Type changes to int <br>
[[0 0]] <br>
Create an array of ones <br>
Default type is float<br>
[[ 1. 1.]]<br>
Type changes to int<br>
[[1 1]]

**Q67**. Write the NumPy program to change the dimension of an array? <br>
**Expected Output-** <br>
6 rows and 0 columns <br>
(6,) <br>
(3, 3) -> 3 rows and 3 columns <br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>
Change array shape to (3, 3) -> 3 rows and 3 columns <br>
[[1 2 3] <br>
[4 5 6]<br>
[7 8 9]]

**Q68.** Write the NumPy program to create a new shape to an array without changing its data ? <br>
Reshape 3x2- <br>
[[1 2] <br>
[3 4] <br>
[5 6]]<br>
Reshape 2x3- <br>
[[1 2 3] <br>
[4 5 6]]

**Q69.** Write the NumPy program to create a new array of 3*5, filled with 2? <br>
Expected Output- <br>
[[2 2 2 2 2]<br>
[2 2 2 2 2]<br>
[2 2 2 2 2]]<br>
[[2 2 2 2 2]<br>
[2 2 2 2 2]<br>
[2 2 2 2 2]]

**Q70.** Write the NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere? <br>
**Expected Output-**<br>
[[ 1. 0. 0.] <br>
[ 0. 1. 0.]<br>
[ 0. 0. 1.]]

**Q71.** Write the NumPy program to split an array of 14 elements into the 3 arrays and each of which has 2, 4, and 8 elements in original order? <br>
**Expected Output:** Original array- [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14] <br>
After splitting- <br>
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

**Q72.** Write the NumPy program to split of an array of shape 4x4 it into two arrays along the second axis ? <br>
**Sample array** -<br>
[[ 0 1 2 3] <br>
[ 4 5 6 7] <br>
[ 8 9 10 11] <br>
[12 13 14 15]] <br>
**Expected Output** <br>
[array([[ 0, 1], [ 4, 5],[ 8, 9],[12, 13]]), array([[ 2, 3], [ 6, 7], [10, 11], [14, 15]]), <br> array([], shape=(4, 0), dtype=int64)]

**Q73.** Write the NumPy program to create a 5x5 matrix with row values ranging from 0 to 4? <br>
Original array- <br>
[[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.]] <br>
Row values ranging from 0 to 4. <br>
[[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.]]

**Q74.** Write the NumPy program to create an array of zeros and three column types (integer, float, character)? <br>
**Expected Output-** <br>
[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley') <br>
(3, 3., b'Gertrude B. Elion')]

**Q75.** Write the NumPy program to remove the negative values in the numpy array with 0? <br>
**Expected Output:** Original array: <br>
[-1 -4 0 2 3 4 5 -6] <br>
Replace the negative values of the said array with 0- <br>
[0 0 0 2 3 4 5 0]

**Q76.** Write the NumPy program to compute the histogram of a set of data? <br>
Sample Output

**Q77.** Write the NumPy program to compute the line graph of a set of data? <br>
Sample Output:

**Q78.** Write the NumPy program to extracts all the elements from second row from given (4x4) array? <br>
**Sample Output:** Original array- <br>
[[ 0 1 2 3] <br>
[ 4 5 6 7]<br>
[ 8 9 10 11]<br>
[12 13 14 15]]<br>
Extracted data- Second row <br>
[4 5 6 7]

**Q79.** Write the NumPy program to extract first element of the second row and fourth element of fourth row from a given (4x4) array? <br>
**Sample Output:** Original array- <br>
[[ 0 1 2 3]<br>
[ 4 5 6 7]<br>
[ 8 9 10 11]<br>
[12 13 14 15]]<br>
Extracted data- First element of the second row and fourth element of fourth row<br>
[ 4 15]

**Q80.** Write the NumPy program to add two arrays A and B of sizes (3,3) and (,3)? <br>
Sample Output: Original arrayArray-1 <br>
[[1 1 1] <br>
[1 1 1] <br>
[1 1 1]] <br>
Array-2 <br>
[0 1 2] <br>
A + B: <br>
[[1 2 3]<br>
[1 2 3]<br>
[1 2 3]]

**Q81.** Write the NumPy program to copy data from a given array to another array? <br>
**Sample Output:** Original array- <br>
[24 27 30 29 18 14] <br>
Copy of the said array- <br>
[24 27 30 29 18 14]

**Q82.** Write the NumPy program to calculate the sum of all columns of the 2D numpy array? <br>
**Sample Output:** Original array- <br>
[[ 0 1 2 3 4 5 6 7 8] <br>
[ 9 10 11 12 13 14 15 16 17] <br>
[18 19 20 21 22 23 24 25 26] <br>
[27 28 29 30 31 32 33 34 35]] <br>
Sum of all columns- <br>
[54 58 62 66 70 74 78 82 86]

**Q83.** Write the NumPy program to calculate averages without NaNs along the given array? <br>
**Sample Output:** Original array- <br>
[[10. 20. 30.] <br>
[40. 50. nan] <br>
[nan 6. nan] <br>
[nan nan nan]] <br>
Averages without NaNs along the said array- <br>
[20. 45. 6. nan]

**Q84.** Create two arrays of six elements. Write the NumPy program to count the number of instances of a value occurring in one array on the condition of another array. <br>
**Sample Output:** Original arrays- <br>
[ 10 -10 10 -10 -10 10] <br>
[0.85 0.45 0.9 0.8 0.12 0.6 ] <br>
Number of instances of a value occurring in one array on the condition of another array: 3 

**Q85.** Write the NumPy program to convert a Python dictionary to a Numpy ndarray ? <br>
Original dictionary- <br>
{'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0}, <br>
'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0}, <br>
'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0}, <br>
'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}} <br>
Type: <class 'dict'> <br>
ndarray- <br>
[[ 1. 0. 0. 2.] <br>
[ 3. 1. 0. -1.] <br>
[ 4. 1. 5. -1.] <br>
[ 3. -1. -1. -1.]] <br>
Type: <class 'numpy.ndarray'>

**Q86.** Write the Numpy program to find and store the non-zero unique rows in an array after comparing each row with other row in the given matrix? <br>
Original array- <br>
[[ 1 1 0] <br>
[ 0 0 0] <br>
[ 0 2 3] <br>
[ 0 0 0] <br>
[ 0 -1 1] <br>
[ 0 0 0]] <br>
Non-zero unique rows- <br>
[[ 1 1 0] <br>
[ 0 2 3] <br>
[ 0 -1 1]]

**Q87.** Write the NumPy program to multiply the matrix by another matrix of complex numbers and create a new matrix of complex numbers? <br>
Sample output: First array- <br>
[ 1.+2.j 3.+4.j] <br>
Second array- <br>
[ 5.+6.j 7.+8.j] <br>
Product of above two arrays- <br>
(70-8j)

**Q88.** Write a NumPy program to generate the matrix product of two Arrays? <br>
**Sample Output:** Matrices and vectors. <br>
x- <br>
[[1, 0], [1, 1]] <br>
y- <br>
[[3, 1], [2, 2]] <br>
Matrix product of above two arrays <br>
[[3 1] <br>
[5 3]]

**Q89.** Write the NumPy program to find roots of the following Polynomials? <br>
a) (x2 - 4x + 7) <br>
b) x4 - 11x3 + 9x2 + 11x ? 10 <br>
**Sample output:** Roots of the first polynomial- <br>
[ 1. 1.] <br>
Roots of the second polynomial- <br>
[ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j <br>
0.91326132-0.4531004j ]

**Q90.** Write the NumPy program to calculate inverse of sine, cosine, and inverse tangent for all elements in a given array? <br>
**Sample output:** Inverse sine- [-1.57079633 0. 1.57079633] <br>
Inverse cosine- [3.14159265 1.57079633 0. ] <br>
Inverse tangent- [-0.78539816 0. 0.78539816]

**Q91.** Write the NumPy program to calculate the difference between in neighbouring elements, element-wise of a given array? <br>
**Sample output:** Original array- <br>
[1 3 5 7 0] <br>
Difference between neighbouring elements, element-wise of the said array- <br>
[ 2 2 2 -7]

**Q92.** Write the Python program to find the maximum and the minimum value of a given flattened array? <br>
Expected Output: Original flattened array- <br>
[[0 1] <br>
[2 3]] <br>
Maximum value of the above flattened array- 3 <br>
Minimum value of the above flattened array- 0

**Q93.** Write the NumPy program to calculate the difference between in the maximum and the minimum values of a given array along the second axis ? <br>
**Expected Output:** Original array- <br>
[[ 0 1 2 3 4 5] <br>
[ 6 7 8 9 10 11]] <br>
Difference between the maximum and the minimum values of the said array- [5 5]

**Q94.** Write the NumPy program to compute the weighted of the given array ? <br>
**Sample Output:** Original array- [0 1 2 3 4]  <br>
Weighted average of the said array- 2.6666666666666665

**Q95.** Write the NumPy program to compute the mean, standard deviation, and the variance of a given array along the second axis? <br>
**Sample output:** Original array-<br>
[0 1 2 3 4 5] <br>
Mean- 2.5 <br> 
std- 1<br>
variance- 2.9166666666666665

**Q96.** Write the Numpy program to compute the covariance matrix of the two given arrays? <br>
**Sample Output:** Original array1- <br>
[0 1 2] <br>
Original array1- <br>
[2 1 0] <br>
Covariance matrix of the said arrays- <br>
[[ 1. -1.] <br>
[-1. 1.]]

**Q97.** Write a NumPy program to compute the cross-correlation of two given arrays ? <br>
**Sample Output:** Original array1 <br>
[0 1 3] <br>
Original array1- <br>
[2 4 5] <br>
Cross-correlation of the said arrays- <br>
[ [ 2.33333333 2.16666667 ] <br>
[ 2.16666667 2.33333333 ] ]

**Q98.** Write the NumPy program to compute Pearson product-moment correlation coefficients of two given arrays? <br>
**Sample Output:** Original array1- <br>
[0 1 3] <br>
Original array1- <br>
[2 4 5] <br>
Pearson product-moment correlation coefficients of the said arrays- <br>
[[1. 0.92857143] <br>
[0.92857143 1. ]]

**Q99.** Write the python program to count the number of occurrences of each value in a given array of non-negative integers? <br>
**Note:** bincount() Function- It count the occurrence of each value in an array of the non- negative integers in the range of the array between the minimum and maximum values including the values that did not occur. <br>
Sample Output: Original array- <br>
[0, 1, 6, 1, 4, 1, 2, 2, 7] <br>
Number of occurrences of each value in array- [1 3 2 0 1 0 1 1]

**Q100.** Write a Numpy program to compute the histogram of nums against the bins? <br>
**Sample Output:** nums- [0.5 0.7 1. 1.2 1.3 2.1]<br>
bins- [0 1 2 3] <br>
Result- (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

**Q101.** Write the Python program to add, subtract, multiply and divide two pandas series ? <br>
**Sample Series-** [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

**Q102.** Write a Python program to convert a dictionary to the Pandas Series? <br>
Sample Series: Original dictionary- <br>
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}<br>
Converted series - <br>
a 100 <br>
b 200 <br>
c 300 <br>
d 400 <br>
e 800 <br>
dtype- int64

**Q103.** Write a python program to change the data type of given a column or a Series? <br>
**Sample Series:** Original Data Series- <br>
0 100 <br>
1 200 <br>
2 python <br>
3 300.12 <br>
4 400 <br> 
dtype- object <br>
Change the said data type to numeric- <br>
0 100.00 <br>
1 200.00<br>
2 NaN<br>
3 300.12<br>
4 400.00<br>
dtype- float64

**Q104.** Write the python pandas program to convert the first column of a DataFrame as a Series? <br>
**Sample Output:** Original DataFrame <br>
col1 col2 col3<br>
0 1 4 7<br>
1 2 5 5<br>
2 3 6 8<br>
3 4 9 12<br>
4 7 5 1<br>
5 11 0 11<br>
1st column as a Series- <br>
0 1<br>
1 2<br>
2 3<br>
3 4<br>
4 7<br>
5 11<br>
Name- col1, dtype- int64 <br>
<class 'pandas.core.series.Series'>

**Q105.** Write a pandas program to create the mean and standard deviation of the data of a given Series? <br>
Sample Output : Original Data Series- <br>
0 1 <br>
1 2 <br>
2 3 <br>
3 4<br>
4 5<br>
5 6<br>
6 7<br>
7 8<br>
8 9<br>
9 5<br>
10 3<br>
dtype- int64 <br>
Mean of the said Data Series- 4.81818181818 <br>
Standard deviation of the said Data Series- 2.52262489555

**Q106.** Write a pandas program to get powers of an array values element-wise? <br>
**Note:**  First array elements raised the powers from the second array.<br>
Sample data: {'X ':[78,85,96,80,86], ' Y ':[84,94,89,83,86],'Z':[86,97,96,72,83]} <br>
**Expected Output:** <br>
X Y Z <br>
0 78 84 86<br>
1 85 94 97<br>
2 96 89 96<br>
3 80 83 72<br>
4 86 86 83

**Q107.** Write the pandas program to get the first 3 rows of a given DataFrame? <br>
Sample Python dictionary data and list labels:  <br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], <br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], <br>
'attempts'- [1, 3, 2, 3, 2, 3, 1, 1, 2, 1 <br>
'qualify'- [ 'yes', 'no', 'yes' , 'no', ' no ', ' yes ', 'yes', 'no', 'no', 'yes' ] } <br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j' ] <br>
**Expected Output:** First three rows of the data frame attempts name qualify score <br>
a 1 Anastasia yes 12.5 <br>
b 3 Dima no 9.0 <br>
c 2 Katherine yes 16.5 <br>

**Q108:** Write the pandas program to select the specified columns and the rows from a given data frame? <br>
Sample Python dictionary data and list labels:  <br>
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame. <br>
exam_data = {'name ': [ 'Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], <br>
'score'- [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], <br>
'attempts'- [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], <br>
'qualify'- ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'] } <br>
labels = ['a ', ' b ', ' c ', ' d ', ' e ', ' f ', ' g ', 'h', 'i', 'j'] <br>
**Expected Output:** <br>
Select specific columns and rows:<br>
  name score <br>
b Dima 9.0 <br>
d James NaN <br>
f Michael 20.0 <br>
g Matthew 14.5

**Q109.** Write the pandas program to calculate mean score for each different student in DataFrame? <br>
Sample Python dictionary data and list labels: <br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], <br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], <br>
'attempts'- [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], <br>
'qualify'- ['yes', 'no', ' yes ', ' no ', ' no ', ' yes ', ' yes ', ' no ', ' no ', ' yes '] } <br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] <br>
**Expected Output:**  <br>
Mean score for each different student in data frame: <br>
13.5625

**Q110.** Write the Pandas program to rename columns of a given DataFrame ? <br>
Sample data: Original data frame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 2 5 8 <br>
2 3 6 9 <br>
New data frame after renaming columns: <br>
Column1 Column2 Column3 <br>
0 1 4 7 <br>
1 2 5 8 <br>
2 3 6 9

**Q111.** Write a pandas program to count city-wise number of people from a given of data set (city, name of the person)? ,br>
Sample data <br>
city Number of people <br>
0 California 4 <br>
1 Georgia 2 <br>
2 Los Angeles 4

**Q112.** Write a pandas program to widen output display to see more columns? <br>
Sample data: Original data frame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 4 5 8 <br>
2 3 6 9 <br>
3 4 7 0 <br>
4 5 8 1

**Q113.** Write a pandas program to convert the data frame column type from string to DateTime? <br>
Sample dataString Date- <br>
0 3/11/2000 <br>
1 3/12/2000 <br>
2 3/13/2000 <br>
dtype- object <br>
Original DataFrame (string to datetime)- <br>

0 2000-03-11  <br>
1 2000-03-12 <br>
2 2000-03-13

**Q114.** Write a pandas program to append the data to an empty DataFrame? <br>
Sample data: <br>
Original DataFrame- After appending some data: col1 col2 0 0 0 1 1 1 2 2 2

**Q115.** Write a pandas program to count the number of columns of a DataFrame? <br>
**Sample Output:** Original DataFrame <br>
col1 col2 col3 <br>
0 1 4 7 <br> 
1 2 5 8 <br>
2 3 6 12 <br>
3 4 9 1 <br>
4 7 5 11 <br>
Number of columns- 3

**Q116.** Write a Pandas program to remove the last n rows of a given DataFrame ? <br>
**Sample Output:** <br>
Original DataFrame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 2 5 5 <br>
2 3 6 8 <br>
3 4 9 12 <br>
4 7 5 1 <br>
5 11 0 11 <br>
After removing last 3 rows of the said DataFrame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 2 5 5 <br>
2 3 6 8 <br>
Link for Datasets <br>
(https://drive.google.com/drive/folders/105ftuIwN9kqyPNEEm3E6IM7LqywjyvJa?usp=sharing)

**Q117.** Write a Pandas program to import excel data (coalpublic2013.xlsx) into a Pandas data frame.

**Q118.** Write a Pandas program to import excel data (coalpublic2013.xlsx) into a data frame and find details where "Mine Name" starts with "P.

**Q119.** Write a Pandas program to import excel data (employee.xlsx) into a Pandas dataframe and find the list of employees where hire_date> 01-01-07.

**Q120.** Write a Pandas program to import excel data (employee.xlsx) into a Pandas dataframe and find a list of the employees of a specified year. 

**Q121.** Write a pandas program to import three datasheets from a given excel data  (coalpublic2013.xlsx ) in to a single dataframe. <br>
**Note:** Structure of three datasheets are same.

**Q122.** Write a pandas program to import three datasheets from a given excel data (employee.xlsx ) into a single data frame and export the result into new Excel file. <br>
**Note:** Structure of three datasheets are same.

**Q123.** Write a pandas program to create the Pivot table with multiple indexes from the data set of the titanic.csv.

**Q124.** Write a Pandas program to create the Pivot table and find survival rate by gender?

**Q125.** Write a pandas program to make partition each of the passengers into 4 categories based on their age. <br>
**Note:** Age categories- (0, 10), (10, 30), (30, 60), (60, 80)

**Q126.** Write a pandas program to create the Pivot table and find survival rate by the gender, age of the different categories of various classes.

**Q127.** Write a pandas program to create the Pivot table and calculate number of women and men were in a particular cabin class.

**Q128.** Write a pandas program to create the Pivot table and separate the gender according to whether they travelled alone or not to get the probability of survival.

**Q129.** Write a pandas program to create the Pivot table and find the probability of survival by class, gender, solo boarding, and the port of embarkation.

**Q130.** Write a pandas program to get current date, oldest date and number of days between Current date and the oldest date of Ufo dataset.

**Q131.** Write a pandas program to get all sighting days of the unidentified flying object (ufo) between 1950-10-10 and 1960-10-10.

**Q132.** Write a Pandas program to extract the year, month, day, hour, minute, second, and weekday from unidentified flying object (UFO) reporting date.

**Q133.** Write a pandas program to count year-country wise frequency of reporting dates of the unidentified flying object(UFO).

**Q134.** Write a pandas program to get the difference (in days) between documented date and reporting date of unidentified flying object (UFO).

**Q135.** Write a pandas program to generate sequences of fixedfrequency dates and time spans.

**Q136.** Write a pandas program to manipulate and convert date times with timezone information.

**Q137.** Write a pandas program to create the graphical analysis of UFO (unidentified flying object) Sightings year.

**Q138.** Write a pandas program to create a comparison of the top 10 years in which the (UFO) was sighted VS each Month.

**Q139.** Write a pandas program to create a heatmap (rectangular data as a colour-encoded matrix) for comparison of top 10 years in which (UFO ) was sighted VS each Month.

**Q140.** Write a pandas program to create a Timewheel of Hour VS Year comparison of the top 10 years in which the (UFO) was sighted.

**Q141.** Write a python program to draw the line using given axis values with the suitable label in the x-axis, y-axis, and a title. <br>
The code snippet gives the output shown in the screenshot:
![alt text](Img1.jpg)

**Q142.** Write a python program to draw the line charts of the financial data of the Alphabet Inc., between October. 3, 2016 to October 7 2016. <br>
Sample Financial data (fdata.csv)- <br>
Date,Open,High,Low,Close <br>
10-03-16,774.25,776.065002,769.5,772.559998 <br>
10-04-16 , 776.030029, 778.710022,772.890015,776.429993 <br>
10-05-16 , 779.309998, 782.070007,775.650024,776.469971 <br>
10-06-16 , 779 , 780.47998,775.539978,776.859985 <br>
10-07-16,779.659973, 779.659973 , 770.75 , 775.080017 <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img2.jpg)

**Q143.** Write a Python program to plot two or more lines on same plot with the suitable legends of each line. <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img3.jpg)

**Q144.** Write a python programming to display a bar chart of the popularity of programming languages. <br>
Sample data: <br>
programming languages- Java, Python, PHP, JavaScript, C#, C++ <br>
Popularity- 22.2, 17.6, 8.8, 8, 7.7 , 6.7 <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img4.jpg)

**Q145.** Write a python programming to display a horizontal bar chart of the popularity of programming languages. <br>
Sample data: <br>
programming languages- Java, Python, PHP, JavaScript, C#, C++ <br>
Popularity- 22.2, 17.6, 8.8, 8, 7.7 , 6.7 <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img5.jpg)

**Q146.** Write a python programming to display a bar chart of the Popularity of programming languages. Increase bottom margin. <br>
Sample data: <br>
programming languages: Java, Python, PHP, JavaScript, C#, C++ <br>
Popularity: 22.2, 17.6, 8.8, 8, 7.7 , 6.7 <br>
The code snippet gives the output shown in the screenshot:  ![alt text](Img6.jpg)

**Q147.** Write a python program to create the bar plot from a DataFrame. <br>
a b c d e <br>
2 4,8,5,7,6 <br>
4 2,3,4,2,6 <br>
6 4,7,4,7, 8 <br>
8 2,6,4,8, 6 <br>
10 2,4,3,3, 2 <br>
The code snippet gives the output shown in the following screenshot:![alt text](Img7.jpg)

**Q148.** Write a python program to draw the scatter plot comparing two subject marks of Mathematics and Science. Use marks of 10 students. <br>
Sample data: <br>
Test Datamath_marks = [88, 92 , 80, 89, 100, 80, 60, 100, 80, 34] <br>
science_marks = [35, 79, 79 , 48, 100, 88, 32, 45, 20, 30] <br>
marks_range = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] 
![alt text](Img8.jpg)

**Q149.** Write a python program to draw the scatter plot for three different groups comparing weights and heights. <br>
The output shown in the screenshot:![alt text](Img9.jpg)

**Q150.** Write a python program to draw a scatter plot to find sea-level rise in past 100 years. <br>
The output shown in the screenshot: ![alt text](Img11.jpg)