**PYTHON** - Practice Subjective

In [1]:
# Import neccessary modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###### **Q1.** Write a Python program to get the string from the given string where all the occurrence of its first char has been changed to  <span>"$"</span> except first char itself? <br> Sample String:'prospect' <br> Expected Result:'pros\\$ect'

In [2]:
sample = "prospects"
c = sample[0]
output = ""
for i in range(len(sample)-1):
    
    if c==sample[i+1]:
        chracter = "$"
    else:
        chracter = sample[i]
#     print(chracter)
    output+=chracter
    
print(output)
    

pro$pect


In [3]:
str1 = ''
output= ["$" if c==sample[i+1] else sample[i] for i in range(len(sample)-1)]
str1.join([str(elem) for elem in output])



'pro$pect'

In [4]:
from collections import Counter
sample = "prospect"

# using collections.Counter() to get count    
count = Counter(sample)
print(count)

Counter({'p': 2, 'r': 1, 'o': 1, 's': 1, 'e': 1, 'c': 1, 't': 1})


**Q2.** Write a Python program to get the single string from the two given strings, and separated by the space and swap the first two characters of each string? <br>
**Sample String :** 'abc', 'xyz'. <br>
**Expected Result:** 'xyc abz'

In [5]:
sample = 'abc','xyz'
print(str(sample))

('abc', 'xyz')


In [6]:
output = sample[0].replace(sample[0][0:2], sample[1][0:2])+" "+ sample[1].replace(sample[1][0:2], sample[0][0:2])
print(output)

xyc abz


**Q3.** Write the Python program to add 'ing' at the end of the given string (length of the string should be at least 3). If given string already ends with 'ing,' then add 'ly' instead. If string length of the given string is less than 3, leave it unchanged? <br>
**Sample string:** ' abc ' <br>
**Expected result:** ' abcing ' <br>
**Sample string:** ' string ' <br>
**Expected result:** ' stringly '

In [ ]:
sample = input()
str1=""
if len(sample)>=3:
    if "ing" in sample:
        print(sample+"ly")
    else:
        print(sample+"ing")        

**Q4.** Write the Python program to find the first appearance of the substring 'not' and 'poor' from the given string, if 'not' follows the 'poor', replace the whole 'not'...' poor' substring with 'good'.Return the resulting string. <br>
**Sample string:** 'The lyrics are not that poor!' 'The lyrics are poor!' <br>
**Expected Result:** 'The lyrics are good!' 'The lyrics are poor!'

In [ ]:
sample = 'The lyrics are not that poor!''The lyrics are poor!'
loc_not = sample.find("not")
loc_poor = sample.find("poor")

if loc_not < loc_poor:
        sample = sample.replace(sample[loc_not:loc_poor + 4],"good")
else:
    print("The string does not contain either not or poor")
    
print(sample)


**Q5.** Write the Python program to remove the characters which have odd index values of a given string.

In [ ]:
sample = "remove the chracters at odd index"

new_str = ""
for c in range(len(sample)):
    if c%2 == 0:
        new_str = new_str + sample[c]
        
print("New string after removing the chracters at odd index-->",new_str)

**Q6.** Write the Python function to get a string made of 4 copies of the last two characters of the specified string (length must be at least 2). <br>
**Sample function and result :** <br>
insert-end ('Python') -> abababab <br>
insert-end('Exercises') -> jkjkjkjk

In [ ]:
def insert_end(sample):
    substr = sample[-2:]
    return 4*substr
    

print(insert_end("Python"))
print(insert_end("Exercises"))

**Q7.** Write the python function to get a string made of its first three characters of a specified string. If the length of the string is less than 3 then return the original string. <br>
**Sample function and result :** <br>
first-three('ipy') -> ipy <br>
first-three('python') -> pyt

In [ ]:
def first_three(sample):
    return sample[0:3]

print(first_three('ipy'))
print(first_three('python'))

**Q8.** Write the python program to print the following floating numbers up to 2 decimal places?

In [ ]:
number = float(input("Enter a number-->"))
print("The number upto 2 decimal places--->",format(number,".2f")) # formatted to two decials places

**Q9.** Write the Python program to format a number with a percentage?

In [ ]:
number = float(input("Enter a number-->"))
print("The number formatted with a percentage--->",format(number,".2%"))

**Q10.** Write the Python program to count occurrences of a substring in a String?

In [ ]:
sample = "I live in India. India is a great country."
print(sample.count("India"))

**Q11.** Write the Python program to count repeated characters in a string. <br>
**Sample string:** ' thequickbrownjumpsoverthelazydog ' <br>
**Expected output:** <br>
o 3 <br>
e 3 <br>
u 2 <br>
h 2 <br>
r 2 <br>
t 2

In [ ]:
from collections import Counter
sample = "thequickbrownjumpsoverthelazydog"

# using collections.Counter() to get count    
count = Counter(sample)

for item in count:
    print(item, count[item])

**Q12.** Write the Python program to print the square and cube symbol in the area of a rectangle and volume of a cylinder? <br>
**Sample output:** <br> The area of the rectangle is 1256.66cm2 <br>
The volume of the cylinder is 1254.725cm3

In [ ]:
def rectangle(length, breadth):
    return length*breadth

def cylinder(radius, height):
    return 3.14*radius*radius*height

print("The area of the rectange is "+ str(rectangle(4,5))+"cm2")
print("The volume of the cylinder is "+ str(cylinder(7,14))+"cm3")

**Q13.** Write the Python program to check if a string contains all letters of the alphabet?

Create a set of the lowercased string and check if it is a superset of the letters of the alphabet:

In [ ]:
import string

all_alpha = set(string.ascii_lowercase)

def contains_all(input_string):
    return set(input_string.lower()) >= all_alpha

input_string = "Pack my box with five dozen liquor jugs"
print(contains_all(input_string))

input_string1 = "I love my India"
print(contains_all(input_string1))

**Q14.** Write the Python program to find the second most repeated word in a given string?

In [ ]:
from collections import Counter
import operator
sample = "thequickbrownjumpsoverthelazydog"

# using collections.Counter() to get count    
count = Counter(sample)

#print(count)
print(max(count.items(), key=operator.itemgetter(1))[1])


**Q15.** Write the Python program to find the minimum window in the given string, which will contains all the characters of another given strings? <br>
**Example 1** <br>
Input : string1 = " PRWSOERIUSFK " <br>
string2 = " OSU " <br>
Output: Minimum window is "OERIUS"

Method 2 ( Efficient Solution )
1. First check if the length of string is less than the length of the given pattern, if yes then “no such window can exist “.
2. Store the occurrence of characters of the given pattern in a hash_pat[].
3. Start matching the characters of pattern with the characters of string i.e. increment count if a character matches.
4. Check if (count == length of pattern ) this means a window is found.
5.If such window found, try to minimize it by removing extra characters from the beginning of the current window.
    Update min_length.
6.Print the minimum length window.


In [ ]:
string1 = "PRWSOERIUSFK"
string2 = "OSU"


**Q16.** Write the Python program to find smallest window that contains all characters of the given string? <br>
**Original Strings:**
asdaewsqgtwwsa <br>
**Smallest window that contains all characters of the said string:**
Daewsqgt

**Q17.** Write the Python program to count number of substrings from a given string of lowercase alphabets with exactly k distinct (given) characters? <br>
**Input a string (lowercase alphabets):** wolf <br>
**Input k:** 4 <br>
**Number of substrings with exactly 4 distinct characters:** 1

**Q18.** Write the Python program to count number of non-empty substrings of the given string? <br>
Input a string: w3resource <br>
Number of substrings: <br>
55

**Q19.** Write the Python program to count number of substrings with same first and last characters of the given string? <br>
**Input a string:** abcd <br>
4

**Q20.** Write the Python program to count the number of strings where the string length is 2 or more, and first and last character are same from a given list of strings. <br>
**Sample List:** ['abc', 'xyz', 'wxw', '1331'] <br>
**Expected Result:** 2

**Q21.** Write the Python program to get a list, sorted in increasing order by the last element in each tuple from the given list of non-empty tuples? <br>
**Sample List-** [ (2, 5), (1, 2), (4, 4), (2, 3), (2, 1) ] <br>
**Expected Result-** [ (2, 1), (1, 2), (2, 3), (4, 4), (2, 5) ]

**Q22.** Write the Python program to remove duplicates from a list?

In [ ]:
sample_list = list(input().strip().split())
print("The input string entered is:", sample_list)
output = set(sample_list)
print("The output list without duplicates is: ",list(output))

**Q23.** Write the Python program to find the list of words that are longer than n from a given list of words?

**Q24.** Write the Python program to print a specified list after removing the 0th, 4th, and 5th elements? <br>
**Sample List-** ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow'] <br>
**Expected Output-** ['Green', 'White', 'Black']

**Q25.** Write the Python program to generate all permutations of a list in Python?

**Q26.** Write the Python program to convert a pair of values into a sorted unique array? <br>
**Original List-** [ (1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ] <br>
**Sorted Unique Data-** [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

**Q27.** Write the Python class to convert an integer to a roman numeral?

In [ ]:
number = int(input("Enter a number :"))


**Q28.** Write the Python class to convert a Roman numeral to an integer?

In [ ]:
roman_number = input("Enter a number :")

**Q29.** Write the Python class to find the validity of the string of the parentheses, '(', ')', '{', '}', '[' and '] and the brackets must be closed in the correct order, example - "()" and "()[]{}" are valid but "[)", "({[)]" and "{{{" are invalid.

**Q30.** Write the Python class to get all possible unique subsets from a set of distinct integers? <br>
**Input-** [4, 5, 6] <br>
**Output-** [[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]

Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number? <br>
**Input:** numbers- [10,20,10,40,50,60,70], target=50 <br>
**Output-** 3, 4

Q32. Write the Python class to find the three elements that sum to zero from the set of n real numbers? <br>
**Input array-** [-25, -10, -7, -3, 2, 4, 8, 10] <br>
**Output-** [[-10, 2, 8], [-7, -3, 10]]

**Q33.** Write the Python class to implement pow(x, n)?

**Q34.** Write the Python class which has two methods get_String and print_String. get_String accept the string from the user and print_String print the string in upper case.

**Q35.** Write the Python class named Rectangle constructed by a and width and the method which will compute the area of the rectangle?

**Q36.** Write the Python class named Circle constructed by the radius and two methods which will compute the area and perimeter of the circle?

**Q37.** Write the Python program to get the class name of an instance in Python?

**Q38.** Write the Python program to count the number of students of individual class? <br>
**Sample data classes** = ( ('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1),)<br>
**Expected Output:** Counter({'VI': 3, 'V': 2, 'VII': 1})

**Q39.** Write the Python program to create an instance of an OrderedDict using the given dictionary and sort dictionary during the creation and print members of the dictionary in reverse order?<br>
**Expected Output:** <br>
Angola 244. <br>
Andorra 376.<br>
Algeria 213.<br>
Afghanistan 93.<br>
Albania 355.<br>
**In reverse order:**<br>
Albania 355.<br>
Afghanistan 93. <br>
Algeria 213. <br>
Andorra 376.<br>
Angola 244.

**Q40.** Write the Python program to compare two unordered lists (not sets)?<br>
**Expected Output:** False

**Q41.** Write the Python program to get an array buffer information? <br>
**Expected Output:** Array buffer start address in memory and number of elements. <br>
(25855056, 2)

**Q42.** Write the Python program to convert an array to an array of machine values and return the bytes representation? <br>
Expected Output: Original arrayA1: array('i', [1, 2, 3, 4, 5, 6]) <br>
Array of bytes: <br>
b'010000000200000003000000040000000500000006000000' 

**Q43.** Write the Python program to read a string and interpreting the string as an array of machine values? <br>
**Expected Output:** array1- array('i', [7, 8, 9, 10]) <br>
Bytes- b'0700000008000000090000000a000000' <br>
array2- array('i', [7, 8, 9, 10]) <br>

**Q44.** Write the Python program to push three items into the heap and return the smallest item from the heap. Also, return and pop the smallest item from the heap? <br>
**Expected Output:** Items in the heap- ('VI', 1). ('VII', 3). ('VIII', 2). <br>
The smallest item in the heap: <br>
('VI', 1).<br>
Pop the smallest item in the heap:<br>
('VII', 2).<br>
('VIII', 3).

**Q45.** Write the Python program to locate the left insertion point for a specified value in sorted order? <br>
**Expected Output:** <br>
4 2

**Q46.** Write the Python program to create the FIFO queue? <br>
**Expected Output:** <br>
0 1 2 3

**Q47.** Write the Python program to calculate the harmonic sum of n-1. <br>
**Note:** The harmonic sum is the sum of reciprocals of the positive Integers? <br>
Example -

**Q48.** Write the NumPy program to create a 2d array with 6 on the border and 0 inside? <br>
**Expected Output :** Original array- <br>
[ [6 6 6 6 6] <br>
[ 6 6 6 6 6] <br>
[ 6 6 6 6 6 ] <br>
[ 6 6 6 6 6 ] <br>
[ 6 6 6 6 ] ]. <br>
6 on the border and 0 inside in the array- <br>
[[ 6 6 6 6 6] <br>
[ 6 0 0 0 6] <br>
[ 6 0 0 0 6]<br>
[ 6 0 0 0 6]<br>
[ 6 6 6 6 6]]

In [ ]:
import numpy as np
arr = np.ones((5,5))*6
# arr =np.array([[6, 6, 6, 6, 6],[ 6, 6, 6, 6, 6],[ 6, 6, 6, 6, 6 ],[ 6, 6, 6, 6, 6 ],[ 6, 6, 6, 6,6]])
print("Original Array:\n",arr)

arr[1:-1,1:-1] = 0
print("6 on the border and 0 inside in the array:\n", arr)


**Q49.** Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern? <br>
Checkerboard pattern- <br>
[[3 9 3 9 3 9 3 9] <br>
[9 3 9 3 9 3 9 3]<br>
[3 9 3 9 3 9 3 9]<br>
[9 3 9 3 9 3 9 3]<br>
[3 9 3 9 3 9 3 9]<br>
[9 3 9 3 9 3 9 3]<br>
[3 9 3 9 3 9 3 9]<br>
[9 3 9 3 9 3 9 3]].

In [ ]:
# Create an matrix of 8X8 dimension and fill it with 9.
check_board = np.ones((8,8),dtype=int)*9

check_board[::2,::2] = 3
check_board[1::2,1::2] = 3
# check_board[1::2,1::2] = 9
print(check_board)


**Q50.** Write the NumPy program to create an empty and a full array. <br>
Expected Output- <br>
[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306] <br>
[1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]<br>
[8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]<br>
[[6 6 6]<br>
[6 6 6]<br>
[6 6 6]]

In [ ]:
arr_empty = np.empty([3,3], dtype=float)
print("Empty Array is-->:\n",arr_empty)

arr_full = np.full([3,3],6)
print("\nFull array is-->\n",arr_full)

**Q51.** Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array. <br>
**Sample Array-** [0, 12, 45.21 ,34, 99.91] <br>
**Expected Output:** Values in Fahrenheit degrees- <br>
[ 0. 12. 45.21 34. 99.91] <br>
Values in Centigrade degrees- <br>
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [ ]:
fahrenheit_values = np.array([0,12,45.21,34,99.91])
print(fahrenheit_values)

print("\nvalues in centrigrade degrees:")
#  Formula to convert : T(°C) = (T(°F) - 32) × 5/9
((fahrenheit_values-32)*5)/9

**Q52.** Write the NumPy program to find the real and imaginary parts of an array of complex numbers? <br>
**Expected Output:** Original array [ 1.00000000+0.j 0.70710678+0.70710678j] <br>
Real part of the array-<br>
[ 1. 0.70710678]<br>
Imaginary part of the array- <br>
[ 0. 0.70710678]

In [ ]:
Z = np.array([1.00000000+0.j,0.70710678+0.70710678j])
print("Real Part-->", Z.real)
print("Imaginary Part",Z.imag)


**Q53.** Write the NumPy program to test whether each element of a 1-D array is also present in the second array? <br>
**Expected Output:** Array1: [ 0 10 20 40 60] <br>
Array2: [0, 40] <br>
Compare each element of array1 and array2 <br>
[ True False False True False]

**Q54.** Write the NumPy program to find common values between two arrays? <br>
**Expected Output:** Array1: [ 0 10 20 40 60] <br>
Array2: [10, 30, 40] <br>
Common values between two arrays- <br>
[10 40]

**Q55.** Write the NumPy program to get the unique elements of an array? <br>
**Expected Output:** Original array- <br>
[10 10 20 20 30 30] <br>
Unique elements of the above array- <br>
[10 20 30] <br>
Original array- <br>
[[1 1] <br>
[2 3]] <br>
Unique elements of the above array- <br>
[1 2 3] 

**Q56.** Write the NumPy program to find the set exclusive-or of two arrays. <br>
Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays? <br>
Array1- [ 0 10 20 40 60 80] <br>
Array2- [10, 30, 40, 50, 70] <br>
Unique values that are in only one (not both) of the input arrays- <br>
[ 0 20 30 50 60 70 80] 

**Q57.** Write the NumPy program to test if all elements in an array evaluate to True ? <br>
Note: 
1. 0 evaluates to False in NumPy.
2. Not a Number (NaN), positive infinity and negative infinity evaluate to True because these are not equal to zero.


In [ ]:
import numpy as np
arr = np.ones((5,5))*6
arr[1:-1,1:-1] = 0
print("Original Array--->\n",arr)
print("\nall elements in an array evaluate to True is", np.all(arr))

**Q58.** Write the NumPy program to test whether any array element along the given axis evaluates to True? <br>
**Note:** 0 evaluates to False in NumPy.

In [ ]:
import numpy as np
arr = np.ones((5,5))*6
arr[4:,:] = 0
print("Original Array--->\n",arr)
print("\nany element along the given axix evaluates to True is", np.any(arr, axis = 1))

**Q59.** Write the NumPy program to construct an array by repeating? <br>
Sample array- [1, 2, 3, 4] <br>
**Expected Output:** Original array <br>
[1, 2, 3, 4] <br>
Repeating 2 times <br>
[1 2 3 4 1 2 3 4] <br>
Repeating 3 times <br>
[1 2 3 4 1 2 3 4 1 2 3 4]

###### numpy.tile(A,reps):<br> This function construct an array by repeating A the number of times given by reps.<br> If reps has length d, the result will have dimension of max(d, A.ndim).

In [ ]:
sample = np.array([1,2,3,4])
print("Original array", sample)
print("Repeating 2 times:-->", np.tile(sample,2))
print("Repeating 2 times:-->", np.tile(sample,3))

**Q60.** Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array? <br>
Original array- [1 2 3 4 5 6] <br>
Maximum Values- 5 <br>
Minimum Values- 0

In [ ]:
orig_array = np.array([1,2,3,4,5,6])
print("Original Array", orig_array)
print("Maximum Values",np.argmax(orig_array)) # argmax gives the indices of the maximum value in an  array
print("Minimum Values",np.argmin(orig_array)) # argmin gives the indices of the maximum value in an array

**Q61.** Write the NumPy program compare two arrays using numpy? <br>
Array a- [1 2] <br>
Array b- [4 5] <br>
a > b <br>
[False False] <br>
a >= b
[False False] <br>
a < b <br>
[ True True] <br>
a <= b <br>
[ True True]

In [ ]:
# Output is an array, element-wise comparison of x1 and x2. 
arr1 = np.array([1,2])
arr2 = np.array([4,5])
print("a > b:", np.greater(arr1,arr2))
print("a >= b:", np.greater_equal(arr1,arr2))
print("a < b:", np.less(arr1,arr2))
print("a <= b:", np.less_equal(arr1,arr2))

**Q62.** Write the NumPy program to sort an along the first, last axis of an array? <br>
Sample array- [[2,5],[4,4]] <br>
**Expected Output:** Original array: <br>
[[4 6] <br>
[2 1]] <br>
Sort along the first axis: <br>
[[2 1] <br>
[4 6]] <br>
Sort along the last axis- <br>
[[1 2] <br>
[4 6]]

In [ ]:
orig_array = np.array([[4,6],[2,1]])
print("Original Array\n",orig_array)

sorted_array1 = np.sort(orig_array, axis=0)
print("Sort along the first axis:\n",sorted_array1)
sorted_array2 = np.sort(sorted_array1, axis=1)
print("Sort along the last axis:\n",sorted_array2)

**Q63.** Write the NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name). <br>
first_names - ( Betsey, Shelley, Lanell, Genesis, Margery ) <br>
last_names - ( Battle, Brien, Plotner, Stahl, Woolum ) <br>
**Expected Output-** <br>
[1 3 2 4 0]

##### Output is not matching with the expected o/p

np.lexsort((b, a))
(i) Perform an indirect sort using a sequence of keys
(ii) Sort by a, then by b
(iii) Return type ndarray of ints Array of indices that sort the keys along the specified axis
(iv) Occupies space as a new array of sorted indices pair wise is returned.

In [ ]:
first_name = ("Betsey", "Shelley", "Lanell", "Genesis", "Margery")
last_name = ("Battle", "Brien", "Plotner", "Stahl", "Woolum")

print(np.lexsort((first_name, last_name)))


**Q64.** Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array? <br>
Original array- <br>
[[ 0 10 20] <br>
[20 30 40]] <br>
Values bigger than 10 = [20 20 30 40] <br>
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

### Not complete solution

In [ ]:
orig_array = np.array([[ 0, 10, 20],
                       [20, 30, 40]])
print(orig_array)
print("\nValues bigger than 10 are -->", orig_array[orig_array>10])

print("their indices are---> ",(orig_array[orig_array>10]))



**Q65.** Write the NumPy program to find the memory size of a NumPy array? <br>
**Expected Output-** 128 bytes

In [ ]:
orig_array = np.array([[ 0, 10, 20],
                       [20, 30, 40],
                      [20,40,60]], dtype = np.int64)

print(orig_array.nbytes)


# print(np.prod(orig_array.size))
# print(orig_array.itemsize)

###### Second Method

In [ ]:
print(np.prod(orig_array.size) * orig_array.itemsize)

**Q66.** Write the NumPy program to create an array of ones and an array of zeros? <br>
**Expected Output:** Create an array of zeros <br>
Default type is float <br>
[[ 0. 0.]] <br>
Type changes to int <br>
[[0 0]] <br>
Create an array of ones <br>
Default type is float<br>
[[ 1. 1.]]<br>
Type changes to int<br>
[[1 1]]

In [ ]:
print("Create an array of Zeros")
zerosArray = np.zeros((2,3))
print(zerosArray)
print("Default type is-->", zerosArray.dtype)

print("\nchanging the dtype to int")
intTypeZerosArray = zerosArray.astype('int64')
print(intTypeZerosArray)

print("\nCreating the arrau of ones")
onesArray = np.ones((2,3))
print(onesArray)
print("Default type is-->", onesArray.dtype)

print("\nchanging the dtype to int")
intTypeOnesArray = onesArray.astype('int64')
print(intTypeOnesArray)

**Q67**. Write the NumPy program to change the dimension of an array? <br>
**Expected Output-** <br>
6 rows and 0 columns <br>
(6,) <br>
(3, 3) -> 3 rows and 3 columns <br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>
Change array shape to (3, 3) -> 3 rows and 3 columns <br>
[[1 2 3] <br>
[4 5 6]<br>
[7 8 9]]

In [ ]:
orig_array = np.arange(1,10)
print(orig_array)

print("The shape of the original array-->", orig_array.shape)

print("\nChange array shape to (3, 3) -> 3 rows and 3 columns")
print("Resulting Array is-->\n",orig_array.reshape((3,3)))

**Q68.** Write the NumPy program to create a new shape to an array without changing its data ? <br>
Reshape 3x2- <br>
[[1 2] <br>
[3 4] <br>
[5 6]]<br>
Reshape 2x3- <br>
[[1 2 3] <br>
[4 5 6]]

In [ ]:
arr = np.arange(1,7)
print("Original Array-->")
print(arr)

print("\nReshape 3X2-->")
print(arr.reshape(3,2))

print("\nReshape 2X3-->")
print(arr.reshape(2,3))

**Q69.** Write the NumPy program to create a new array of 3*5, filled with 2? <br>
Expected Output- <br>
[[2 2 2 2 2]<br>
[2 2 2 2 2]<br>
[2 2 2 2 2]]


In [ ]:
arr = np.ones((3,5))*2
print("Expected Output-->\n",arr)

**Q70.** Write the NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere? <br>
**Expected Output-**<br>
[[ 1. 0. 0.] <br>
[ 0. 1. 0.]<br>
[ 0. 0. 1.]]

In [ ]:
arr = np.eye(3)
print(arr)


**Q71.** Write the NumPy program to split an array of 14 elements into the 3 arrays and each of which has 2, 4, and 8 elements in original order? <br>
**Expected Output:** Original array- [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14] <br>
After splitting- <br>
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [ ]:
arr = np.arange(1,15)
print("Original Array-->", arr)
print("After Splitting-->\n",np.split(arr,[2,6]))

**Q72.** Write the NumPy program to split of an array of shape 4x4 it into two arrays along the second axis ? <br>
**Sample array** -<br>
[[ 0 1 2 3] <br>
[ 4 5 6 7] <br>
[ 8 9 10 11] <br>
[12 13 14 15]] <br>
**Expected Output** <br>
[array([[ 0, 1], [ 4, 5],[ 8, 9],[12, 13]]), array([[ 2, 3], [ 6, 7], [10, 11], [14, 15]]), <br> array([], shape=(4, 0), dtype=int64)]

In [ ]:
sampleArray = np.arange(0,16).reshape(4,4)
print(sampleArray)

print(np.hsplit(sampleArray,2))

**Q73.** Write the NumPy program to create a 5x5 matrix with row values ranging from 0 to 4? <br>
Original array- <br>
[[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.] <br>
[ 0. 0. 0. 0. 0.]] <br>
Row values ranging from 0 to 4. <br>
[[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.] <br>
[ 0. 1. 2. 3. 4.]]

In [ ]:
origArray = np.zeros((5,5))
print(origArray)

print("\nRow values ranging from 0 to 4")
print(origArray+[0,1,2,3,4])


**Q74.** Write the NumPy program to create an array of zeros and three column types (integer, float, character)? <br>
**Expected Output-** <br>
[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley') <br>
(3, 3., b'Gertrude B. Elion')]

In [ ]:
b'Albert Einstein'

##### Not completed
Understand Custom DataTypes in Numpy

In [ ]:
arr = np.zeros((3,0),dtype = ('i8,f8,S50'))
print(arr.dtype) 
new_dat = [(1, 2., 'Albert Einstein'),(2, 2., 'Edmond Halley'),(3, 3., 'Gertrude B. Elion')]
arr[:]= new_dat
print(arr)

In [ ]:
x = np.zeros((3,), dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', 'S30')])
print(x)
x + [(1, 2., b"Albert Einstein"), (2, 2., b"Edmond Halley"), (3, 3., b"Gertrude B. Elion")]

In [ ]:
np.array([(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]).shape

In [ ]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)

**Q75.** Write the NumPy program to remove the negative values in the numpy array with 0? <br>
**Expected Output:** Original array: <br>
[-1 -4 0 2 3 4 5 -6] <br>
Replace the negative values of the said array with 0- <br>
[0 0 0 2 3 4 5 0]

In [ ]:
orig_Array = np.array([-1,-4, 0, 2, 3, 4, 5, -6])
print(orig_Array)

orig_Array[orig_Array<0] = 0
print("\nReplace the negative values of the said array with 0-->\n")
print(orig_Array)

**Q76.** Write the NumPy program to compute the histogram of a set of data? <br>
Sample Output: ![alt text](img12.jpg)

not complted

In [ ]:
import matplotlib.pyplot as plt
rng = np.random.RandomState(10)  # deterministic random data
a = np.hstack((rng.normal(size=1000), rng.normal(loc=5, scale=2, size=1000)))
_ = plt.hist(a, bins='auto')  # arguments are passed to np.histogram
plt.title("Histogram with 'auto' bins")
# Text(0.5, 1.0, "Histogram with 'auto' bins")
plt.show()

**Q77.** Write the NumPy program to compute the line graph of a set of data? <br>
Sample Output: ![alt text](img13.jpg)

**Q78.** Write the NumPy program to extracts all the elements from second row from given (4x4) array? <br>
**Sample Output:** Original array- <br>
[[ 0 1 2 3] <br>
[ 4 5 6 7]<br>
[ 8 9 10 11]<br>
[12 13 14 15]]<br>
Extracted data- Second row <br>
[4 5 6 7]

In [ ]:
sampleArray = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11], [12,13,14,15]])
print(sampleArray)

print("Extracted Data - Second Row-->", sampleArray[1,:])

**Q79.** Write the NumPy program to extract first element of the second row and fourth element of fourth row from a given (4x4) array? <br>
**Sample Output:** Original array- <br>
[[ 0 1 2 3]<br>
[ 4 5 6 7]<br>
[ 8 9 10 11]<br>
[12 13 14 15]]<br>
Extracted data- First element of the second row and fourth element of fourth row<br>
[ 4 15]

In [ ]:
sampleArray = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11], [12,13,14,15]])
print(sampleArray)

print("First element of the second row and fourth element of the fourth row-->", sampleArray[[1,3],[0,3]])

**Q80.** Write the NumPy program to add two arrays A and B of sizes (3,3) and (,3)? <br>
Sample Output: Original arrayArray-1 <br>
[[1 1 1] <br>
[1 1 1] <br>
[1 1 1]] <br>
Array-2 <br>
[0 1 2] <br>
A + B: <br>
[[1 2 3]<br>
[1 2 3]<br>
[1 2 3]]

In [ ]:
origArray1 = np.array([[1,1,1],
                      [1,1,1],
                      [1,1,1]])
origArray2 = np.array([0,1,2])

print(origArray1 + origArray2)



**Q81.** Write the NumPy program to copy data from a given array to another array? <br>
**Sample Output:** Original array- <br>
[24 27 30 29 18 14] <br>
Copy of the said array- <br>
[24 27 30 29 18 14]

In [ ]:
origArray = np.array([24,27,30,29,18,14])

x = np.copy(origArray, order='K') # ‘K’ means match the layout of a as closely as possible

print("Copy of the said array",x)

**Q82.** Write the NumPy program to calculate the sum of all columns of the 2D numpy array? <br>
**Sample Output:** Original array- <br>
[[ 0 1 2 3 4 5 6 7 8] <br>
[ 9 10 11 12 13 14 15 16 17] <br>
[18 19 20 21 22 23 24 25 26] <br>
[27 28 29 30 31 32 33 34 35]] <br>
Sum of all columns- <br>
[54 58 62 66 70 74 78 82 86]

In [ ]:
origArray = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
                        [9, 10, 11, 12, 13, 14, 15, 16, 17],
                        [18, 19, 20, 21, 22, 23, 24, 25, 26],
                        [27, 28, 29, 30, 31, 32, 33, 34, 35]])

print("original Array-->\n", origArray)

print("\nsum of all columns-->")
print(np.sum(origArray,axis = 0))

**Q83.** Write the NumPy program to calculate averages without NaNs along the given array? <br>
**Sample Output:** Original array- <br>
[[10. 20. 30.] <br>
[40. 50. nan] <br>
[nan 6. nan] <br>
[nan nan nan]] <br>
Averages without NaNs along the said array- <br>
[20. 45. 6. nan]

In [ ]:
from numpy import nan
origArray = np.array([[10., 20., 30.],
                      [40., 50., nan],
                      [nan, 6., nan],
                      [nan, nan, nan]])
print(origArray)

print("Averages without NaNs along the said array-->")

print(np.nanmean(origArray,axis = 1)) # (10+20+30)/3 = 20


**Q84.** Create two arrays of six elements. Write the NumPy program to count the number of instances of a value occurring in one array on the condition of another array. <br>
**Sample Output:** Original arrays- <br>
[ 10 -10 10 -10 -10 10] <br>
[0.85 0.45 0.9 0.8 0.12 0.6 ] <br>
Number of instances of a value occurring in one array on the condition of another array: 3 

calculate c as the number of 1's in a that occur when b > .5, so in this case `c = 3'.

In [ ]:
array1 = np.array([10, -10, 10, -10, -10, 10])
array2 = np.array([0.85, 0.45, 0.9,0.8,0.12,0.6])
print(f"Original Arrays-->\n{array1}\n {array2}")

print("Number of instances of a value occuring in one array on the condition of another of another array:",
       np.sum((array1 == -10) & (array2 > 0.2)) ) # does element-by-element comparision.
                                                   # When both the conditions are true, it returns true.

**Q85.** Write the NumPy program to convert a Python dictionary to a Numpy ndarray ? <br>
Original dictionary- <br>
{'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0}, <br>
'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0}, <br>
'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0}, <br>
'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}} <br>
Type: <class 'dict'> <br>
ndarray- <br>
[[ 1. 0. 0. 2.] <br>
[ 3. 1. 0. -1.] <br>
[ 4. 1. 5. -1.] <br>
[ 3. -1. -1. -1.]] <br>
Type: <class 'numpy.ndarray'>

In [ ]:
origDict = {'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
            'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
            'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
            'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
print("Original Dictionary\n",origDict)

# print("ndarray",np.array(tuple(origDict.keys())))

data = list(origDict.items())
an_array = np.array(data)
print(an_array)

0**Q86.** Write the Numpy program to find and store the non-zero unique rows in an array after comparing each row with other row in the given matrix? <br>
Original array- <br>
[[ 1 1 0] <br>
[ 0 0 0] <br>
[ 0 2 3] <br>
[ 0 0 0] <br>
[ 0 -1 1] <br>
[ 0 0 0]] <br>
Non-zero unique rows- <br>
[[ 1 1 0] <br>
[ 0 2 3] <br>
[ 0 -1 1]]

In [ ]:
r[np.all(r == 0, axis=1)]
array([[ 0.,  0.,  0.]])
>>> r[~np.all(r == 0, axis=1)]
array([[-1.41421356, -0.70710678, -0.70710678],
       [ 0.        , -1.22474487, -1.22474487]])

In [ ]:
origArray = np.array([[1, 1, 0],[0, 0, 0],[0, 2, 3],[0, 0, 0], [0, -1, 1],[0, 0, 0]])
print(origArray)

print("\nNon-zero unique rows")
# print(origArray[np.nonzero(origArray)])

# print(origArray[np.all(origArray == 0, axis = 1)])
print(origArray[~np.all(origArray == 0, axis = 1)])





**Q87.** Write the NumPy program to multiply the matrix by another matrix of complex numbers and create a new matrix of complex numbers? <br>
Sample output: First array- <br>
[ 1.+2.j 3.+4.j] <br>
Second array- <br>
[ 5.+6.j 7.+8.j] <br>
Product of above two arrays- <br>
(70-8j)

In [ ]:
firstArray = np.array([1+2j, 3+4j])
secondArray = np.array([5+6j, 7+8j])
print("First Array-->",firstArray)
print("Second Array-->",secondArray)

print("Product of above two arrays-->",np.vdot(firstArray,secondArray))

**Q88.** Write a NumPy program to generate the matrix product of two Arrays? <br>
**Sample Output:** Matrices and vectors. <br>
x- <br>
[[1, 0], [1, 1]] <br>
y- <br>
[[3, 1], [2, 2]] <br>
Matrix product of above two arrays <br>
[[3 1] <br>
[5 3]]

In [ ]:
x = np.mat('1,0;,1,1')
print("x-->\n", x)

y = np.mat('3,1;2,2')
print("y-->\n",y)

print("\nMatrix product of above two arrays")

print(np.dot(x,y))

**Q89.** Write the NumPy program to find roots of the following Polynomials? <br>
a) (x2 - 4x + 7) <br>
b) x4 - 11x3 + 9x2 + 11x+10 <br>
**Sample output:** Roots of the first polynomial- <br>
[ 1. 1.] <br>
Roots of the second polynomial- <br>
[ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j 0.91326132-0.4531004j ]

In [ ]:
coeff1 = [1,-4,7]
print("the roots of the First polynomials x2-4x+7 is",np.roots(coeff1))

coeff2 = [1,-11, 9,11,10]
print("the roots of the second polynomials x4-11x3+9x2+11x+10 is",np.roots(coeff2))


**Q90.** Write the NumPy program to calculate inverse of sine, cosine, and inverse tangent for all elements in a given array? <br>
**Sample output:** Inverse sine- [-1.57079633 0. 1.57079633] <br>
Inverse cosine- [3.14159265 1.57079633 0. ] <br>
Inverse tangent- [-0.78539816 0. 0.78539816]

In [ ]:
sampleArray = np.array([-1, 1])

print("Inverse Sine", np.arcsin(sampleArray))

print("Inverse CoSine", np.arccos(sampleArray))

print("Inverse tangent", np.arctan(sampleArray))


**Q91.** Write the NumPy program to calculate the difference between in neighbouring elements, element-wise of a given array? <br>
**Sample output:** Original array- <br>
[1 3 5 7 0] <br>
Difference between neighbouring elements, element-wise of the said array- <br>
[ 2 2 2 -7]

In [ ]:
originalArray = np.array([1,3,5,7,0])
print("original Array-->", originalArray)

print("Diffrence between neighbouring elements, element-wise of the said array-->")

np.diff(originalArray)



**Q92.** Write the Python program to find the maximum and the minimum value of a given flattened array? <br>
Expected Output: Original flattened array- <br>
[[0 1] <br>
[2 3]] <br>
Maximum value of the above flattened array- 3 <br>
Minimum value of the above flattened array- 0

In [ ]:
origArray = np.array([[0,1],[2,3]])
print("Original Flattened Array\n", origArray)

print("Maximum value of the above flattened array-->", np.max(origArray))
print("Minimum value of the above flattened array-->", np.min(origArray))


**Q93.** Write the NumPy program to calculate the difference between in the maximum and the minimum values of a given array along the second axis ? <br>
**Expected Output:** Original array- <br>
[[ 0 1 2 3 4 5] <br>
[ 6 7 8 9 10 11]] <br>
Difference between the maximum and the minimum values of the said array- [5 5]

In [ ]:
np.max(origArray,)

In [ ]:
origArray = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
print("original Array-->\n", origArray)

print("\nDifference between the maximum and the minimum values of the said array:",np.max(origArray,axis=1)-np.min(origArray,axis=1))

**Q94.** Write the NumPy program to compute the weighted of the given array ? <br>
**Sample Output:** Original array- [0 1 2 3 4]  <br>
Weighted average of the said array- 2.6666666666666665

In [ ]:
import numpy as np
origArray = np.array([0,1,2,3,4])
print("origArray", origArray)

print("Weighted Average of the said Array-",np.average(origArray, weights = [1./5, 2./5, 1./5, 1./10, 1./10]))



**Q95.** Write the NumPy program to compute the mean, standard deviation, and the variance of a given array along the second axis? <br>
**Sample output:** Original array-<br>
[0 1 2 3 4 5] <br>
Mean- 2.5 <br> 
std- 1<br>
variance- 2.9166666666666665

In [ ]:
origArray = np.array([0,1,2,3,4,5])
print("mean", np.mean(origArray))
print("Standard Deviation",np.std(origArray))
print("Variance",np.var(origArray))


**Q96.** Write the Numpy program to compute the covariance matrix of the two given arrays? <br>
**Sample Output:** Original array1- <br>
[0 1 2] <br>
Original array1- <br>
[2 1 0] <br>
Covariance matrix of the said arrays- <br>
[[ 1. -1.] <br>
[-1. 1.]]

In [ ]:
origArray1 = np.array([0,1,2])
origArray2 = np.array([2,1,0])
print("Original Array1-->\n",origArray1)
print("Original Array2-->\n",origArray2)

print("\nCovariance matrix of the said arrays-")
print(np.cov(origArray1,origArray2))


**Q97.** Write a NumPy program to compute the cross-correlation of two given arrays ? <br>
**Sample Output:** Original array1 <br>
[0 1 3] <br>
Original array1- <br>
[2 4 5] <br>
Cross-correlation of the said arrays- <br>
[ [ 2.33333333 2.16666667 ] <br>
[ 2.16666667 2.33333333 ] ]

In [ ]:
origArray1 = np.array([0,1,3])
origArray2 = np.array([2,4,5])
print("Original Array 1-",origArray1)
print("Original Array 2-",origArray2)

print("\nCross-correlation of the said arrays-")
print(np.cov(origArray1,origArray2))

**Q98.** Write the NumPy program to compute Pearson product-moment correlation coefficients of two given arrays? <br>
**Sample Output:** Original array1- <br>
[0 1 3] <br>
Original array1- <br>
[2 4 5] <br>
Pearson product-moment correlation coefficients of the said arrays- <br>
[[1. 0.92857143] <br>
[0.92857143 1. ]]

In [ ]:
origArray1 = np.array([0,1,3])
origArray2 = np.array([2,4,5])
print("Original Array 1-",origArray1)
print("Original Array 2-",origArray2)

print("Pearson product-moment correlation coefficients of the said arrays-")
print(np.corrcoef(origArray1,origArray2))


**Q99.** Write the python program to count the number of occurrences of each value in a given array of non-negative integers? <br>
**Note:** bincount() Function- It count the occurrence of each value in an array of the non- negative integers in the range of the array between the minimum and maximum values including the values that did not occur. <br>
Sample Output: Original array- <br>
[0, 1, 6, 1, 4, 1, 2, 2, 7] <br>
Number of occurrences of each value in array- [1 3 2 0 1 0 1 1]

bincount returns the size of each 'bin' for each value from 0 to the largest value in the array it is called on.

e.g.

>>> np.bincount(np.array([0,1,2,3,4]))
array([1, 1, 1, 1, 1])
Above it returns five 1's, since there is one of each value from the smallest value: 0 to the largest value: 4.

>>> np.bincount(np.array([0, 1, 1, 1, 2, 3, 7]))
array([1, 3, 1, 1, 0, 0, 0, 1])
Above it returns the amount of 0's, 1's, 2's, 3's, 4's (0), 5's (0), 6's (0) and 7's.

In [ ]:
origArray = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
print("Original Array",origArray)

print("Number of occurrences of each value in array-", np.bincount(origArray))

**Q100.** Write a Numpy program to compute the histogram of nums against the bins? <br>
**Sample Output:** nums- [0.5 0.7 1. 1.2 1.3 2.1]<br>
bins- [0 1 2 3] <br>
Result- (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

All but the last (righthand-most) bin is half-open. In other words, if bins is:

[1, 2, 3, 4]
then the first bin is [1, 2) (including 1, but excluding 2) and the second [2, 3). The last bin, however, is [3, 4], which includes 4.

In [ ]:
nums = np.array([0.5, 0.7, 1., 1.2, 1.3, 2.1])
bins = [0,1,2,3]
np.histogram(nums, bins)

**Q101.** Write the Python program to add, subtract, multiply and divide two pandas series ? <br>
**Sample Series-** [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
ser1 = list(map(int, input().split()))
a = pd.Series(ser1, index=['a', 'b', 'c', 'd','e'])
ser2 = list(map(int, input().split()))
b = pd.Series(ser2, index=['a', 'b', 'c', 'd','e'])

# Add Series
print("Series Addition\n",a.add(b))

# Subtract Series
print("Series Subtraction\n", a.subtract(b))

# Multiply Series
print("Series Multiplication\n",a.multiply(b))

# Divide Series
print("Series Divide\n",a.divide(b))

**Q102.** Write a Python program to convert a dictionary to the Pandas Series? <br>
Sample Series: Original dictionary- {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}<br>
Converted series - <br>
a 100 <br>
b 200 <br>
c 300 <br>
d 400 <br>
e 800 <br>
dtype- int64

In [ ]:
import pandas as pd
orig_dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
print("Original dictionary-->",orig_dict)
df = pd.Series(orig_dict)
print("\nConverted Series-->\n",df)

**Q103.** Write a python program to change the data type of given column or Series? <br>
**Sample Series:** Original Data Series- <br>
0 100 <br>
1 200 <br>
2 python <br>
3 300.12 <br>
4 400 <br> 
dtype- object <br>
Change the said data type to numeric- <br>
0 100.00 <br>
1 200.00<br>
2 NaN<br>
3 300.12<br>
4 400.00<br>
dtype- float64

In [ ]:
import numpy as np
data = np.array([[0,100],
                [1,200],
                [2,'python'],
                [3, 300.12],
                [4, 400]])
orig_df = pd.DataFrame(data, columns=['a','b'], index=None)
print(orig_df)
pd.to_numeric(orig_df["b"],errors='coerce')

**Q104.** Write the python pandas program to convert the first column of a DataFrame as a Series? <br>
**Sample Output:** Original DataFrame <br>
col1 col2 col3<br>
0 1 4 7<br>
1 2 5 5<br>
2 3 6 8<br>
3 4 9 12<br>
4 7 5 1<br>
5 11 0 11<br>
1st column as a Series- <br>
0 1<br>
1 2<br>
2 3<br>
3 4<br>
4 7<br>
5 11<br>
Name- col1, dtype- int64 <br>
<class 'pandas.core.series.Series'>

In [ ]:
data = np.array([[1,4,7],
                [2,5,5],
                [3,6,8],
                [4, 9, 12],
                [7,5,1],
                [11,0,11]])
orig_df = pd.DataFrame(data, columns=['col1','col2','col3'], index=None)
print(orig_df)
print('First Column as Series:')
pd.Series(orig_df["col1"])

**Q105.** Write a pandas program to create the mean and standard deviation of the data of a given Series? <br>
Sample Output : Original Data Series- <br>
0 1 <br>
1 2 <br>
2 3 <br>
3 4<br>
4 5<br>
5 6<br>
6 7<br>
7 8<br>
8 9<br>
9 5<br>
10 3<br>
dtype- int64 <br>
Mean of the said Data Series- 4.81818181818 <br>
Standard deviation of the said Data Series- 2.52262489555

In [ ]:
print("Original Data Series-->")
data = np.array([1,2,3,4,5,6,7,8,9,5,3])

ser1 = pd.Series(data)
print(ser1)

# mean and std of the data series
mean = ser1.mean()
std = ser1.std()
print(f"Mean of the said Data Series - {mean}")
print(f"\nstandard deviation of the said Data Series - {std}")


**Q106.** Write a pandas program to get powers of an array values element-wise? <br>
**Note:**  First array elements raised the powers from the second array.<br>
Sample data: {'X ':[78,85,96,80,86], ' Y ':[84,94,89,83,86],'Z':[86,97,96,72,83]} <br>
**Expected Output:** <br>
X Y Z <br>
0 78 84 86<br>
1 85 94 97<br>
2 96 89 96<br>
3 80 83 72<br>
4 86 86 83

In [ ]:
sample_dict = {'X ':[78,85,96,80,86], ' Y ':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df = pd.DataFrame.from_dict(sample_dict)
print(df)

**Q107.** Write the pandas program to get the first 3 rows of a given DataFrame? <br>
Sample Python dictionary data and list labels:  <br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], <br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], <br>
'attempts'- [1, 3, 2, 3, 2, 3, 1, 1, 2, 1 <br>
'qualify'- [ 'yes', 'no', 'yes' , 'no', ' no ', ' yes ', 'yes', 'no', 'no', 'yes' ] } <br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j' ] <br>
**Expected Output:** First three rows of the data frame attempts name qualify score <br>
a 1 Anastasia yes 12.5 <br>
b 3 Dima no 9.0 <br>
c 2 Katherine yes 16.5 <br>

In [ ]:
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 
                      'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score':[12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts':[1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
              'qualify':['yes', 'no', 'yes' , 'no', 'no', ' yes ', 'yes', 'no', 'no','yes' ] }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j' ]
exam_df = pd.DataFrame(exam_data, index=labels)
exam_df[["attempts","name","qualify","score"]].head(3)

**Q108:** Write the pandas program to select the specified columns and the rows from a given data frame? <br>
Sample Python dictionary data and list labels:  <br>
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame. <br>
exam_data = {'name ': [ 'Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], <br>
'score'- [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], <br>
'attempts'- [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], <br>
'qualify'- ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'] } <br>
labels = ['a ', ' b ', ' c ', ' d ', ' e ', ' f ', ' g ', 'h', 'i', 'j'] <br>
**Expected Output:** <br>
Select specific columns and rows:<br>
  name score <br>
b Dima 9.0 <br>
d James NaN <br>
f Michael 20.0 <br>
g Matthew 14.5

In [ ]:
exam_data = {'name': [ 'Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score':[12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify':['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'] }
labels = ['a ', ' b ', ' c ', ' d ', ' e ', ' f ', ' g ', 'h', 'i', 'j']

exam_df = pd.DataFrame(exam_data, index=labels)

exam_df[["name","score"]].iloc[[1,3,5,6]]

**Q109.** Write the pandas program to calculate mean score for each different student in DataFrame? <br>
Sample Python dictionary data and list labels: <br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], <br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], <br>
'attempts'- [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], <br>
'qualify'- ['yes', 'no', ' yes ', ' no ', ' no ', ' yes ', ' yes ', ' no ', ' no ', ' yes '] } <br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] <br>
**Expected Output:**  <br>
Mean score for each different student in data frame: <br>
13.5625

In [ ]:
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
            'score':[12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
            'attempts':[1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
            'qualify':['yes', 'no', ' yes ', ' no ', ' no ', ' yes ', ' yes ', ' no ', ' no ', ' yes '] }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

exam_DataFrame = pd.DataFrame(exam_data,index=labels)
print("Original DataFrame-->\n",exam_DataFrame)
scoreMean = exam_DataFrame["score"].mean(skipna = True)
print("\nMean Score for each diffrent student in data Frame-->", scoreMean)

**Q110.** Write the Pandas program to rename columns of a given DataFrame ? <br>
Sample data: Original data frame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 2 5 8 <br>
2 3 6 9 <br>
New data frame after renaming columns: <br>
Column1 Column2 Column3 <br>
0 1 4 7 <br>
1 2 5 8 <br>
2 3 6 9

In [ ]:
origData = np.array([[1,4,7],
                         [2,5,8],
                         [3,6,9]])
origDataFrame = pd.DataFrame(origData,columns = ['col1','col2', 'col3'])
print("Original Data Frame-->\n",origDataFrame)

print("\nNew Data Frame after renaming columns:")
print(origDataFrame.rename(columns={"col1":"Column 1","col2":"Column 2","col3":"Column 3"}))

**Q111.** Write a pandas program to count city-wise number of people from a given of data set (city, name of the person)? <br>
Sample Output: <br>
city Number of people <br>
0 California 4 <br>
1 Georgia 2 <br>
2 Los Angeles 4

#### Not Completed

In [ ]:
sampleArray = np.array([["California","Liam"],
                       ["Georgia", "Fiona"],
                        ["Los Angeles","Ivor"],
                        ["Georgia","Gary"],
                        ["California","Fiona"],
                        ["Georgia","Stevan"],
                        ["Los Angeles","Shauna"],
                        ["California", "Harry"],
                        ["California","Charlie"],
                        ["Los Angeles", "Tom Hanks"]])
sampleData = pd.DataFrame(sampleArray, columns = ["City", "Name of person"])     
                                             
print(sampleData)

# Count city-wise number of people from a given data set
sampleData.groupby(["City"]).agg(Number_of_People=('City','count'))



**Q112.** Write a pandas program to widen output display to see more columns? <br>
Sample data: Original data frame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 4 5 8 <br>
2 3 6 9 <br>
3 4 7 0 <br>
4 5 8 1

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
# pd.set_option('display.expand_frame_repr', False)
origArray = np.array([[1,4,7],
                     [4,5,8],
                     [3,6,9],
                     [4,7,0],
                     [5,8,1]])
origDataFrame = pd.DataFrame(origArray, columns = ['col1','col2','col3'])
print(origDataFrame)

**Q113.** Write a pandas program to convert the data frame column type from string to DateTime? <br>
Sample dataString Date- <br>
0 3/11/2000 <br>
1 3/12/2000 <br>
2 3/13/2000 <br>
dtype- object <br>
Original DataFrame (string to datetime)- <br>

0 2000-03-11  <br>
1 2000-03-12 <br>
2 2000-03-13

In [ ]:
 
sampleData = pd.DataFrame(["3/11/2000","3/12/2000","3/13/2000"], columns = ["Date"])
print("Original DataFrame-->\n",sampleData)


print("\nOriginal Data Frame-->\n",pd.to_datetime(sampleData["Date"]))


**Q114.** Write a pandas program to append the data to an empty DataFrame? <br>
Sample data: <br>
Original DataFrame- After appending some data: col1 col2 0 0 0 1 1 1 2 2 2

In [ ]:
sampleData = pd.DataFrame([],columns = ["col1","col2"])
print(sampleData)

print("DataFrame after appending some data")
sampleData.append(pd.DataFrame({"col1":[0,0,1,1,2],'col2':[0,1,1,2,2]}), ignore_index = True)

**Q115.** Write a pandas program to count the number of columns of a DataFrame? <br>
**Sample Output:** Original DataFrame <br>
col1 col2 col3 <br>
0 1 4 7 <br> 
1 2 5 8 <br>
2 3 6 12 <br>
3 4 9 1 <br>
4 7 5 11 <br>
Number of columns- 3

In [ ]:
origArray = np.array([[1,4,7],[2,5,8],[3,6,12],[4,9,1],[7,5,11]])
origData = pd.DataFrame(origArray, columns = ['col1','col2','col3'])
print("Original DataFrame\n", origData)

print("\nnumber of columns-->", len(origData.columns))

**Q116.** Write a Pandas program to remove the last n rows of a given DataFrame ? <br>
**Sample Output:** <br>
Original DataFrame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 2 5 5 <br>
2 3 6 8 <br>
3 4 9 12 <br>
4 7 5 1 <br>
5 11 0 11 <br>
After removing last 3 rows of the said DataFrame <br>
col1 col2 col3 <br>
0 1 4 7 <br>
1 2 5 5 <br>
2 3 6 8 


In [ ]:
origData = np.array([[1,4,7],[2,5,5],[3,6,8],[4,9,12],[7,5,1],[11,0,11]])
origDataFrame = pd.DataFrame(origData, columns = ['col1','col2','col3'])
print("Original Data Frame\n", origDataFrame)

n=3

print("\nAfter removing last 3 rows of the said Data Frame-->")
origDataFrame.drop(origDataFrame.tail(n).index,inplace=True)
print(origDataFrame)

Link for Datasets <br>
(https://drive.google.com/drive/folders/105ftuIwN9kqyPNEEm3E6IM7LqywjyvJa?usp=sharing)

**Q117.** Write a Pandas program to import excel data (coalpublic2013.xlsx) into a Pandas data frame.

In [ ]:
coalDataFrame = pd.read_excel("coalpublic2013.xlsx")
coalDataFrame.head()

**Q118.** Write a Pandas program to import excel data (coalpublic2013.xlsx) into a data frame and find details where "Mine Name" starts with "P.

In [ ]:
#startswith Tests if the start of each string element matches a pattern
coalDataFrame[coalDataFrame["Mine_Name"].str.startswith("P")]

**Q119.** Write a Pandas program to import excel data (employee.xlsx) into a Pandas dataframe and find the list of employees where hire_date> 01-01-07.

In [ ]:
empDataFrame = pd.read_excel("employee.xlsx")
empDataFrame.head()

In [ ]:
empDataFrame.info()

In [ ]:
#list of employees where hire_date> 01-01-07
empDataFrame[empDataFrame["hire_date"]>pd.to_datetime("01-01-07")]

**Q120.** Write a Pandas program to import excel data (employee.xlsx) into a Pandas dataframe and find a list of the employees of a specified year. 

In [ ]:
year = 2007  # employees to be found from the year
# first find the unique year
empDataFrame["JoinYear"]= empDataFrame["hire_date"].dt.year

# empDataFrame.groupby("JoinYear").count()

empDataFrame[empDataFrame["JoinYear"]==year]

**Q121.** Write a pandas program to import three datasheets from a given excel data  (coalpublic2013.xlsx ) in to a single dataframe. <br>
**Note:** Structure of three datasheets are same.

In [ ]:
coalPublicData = pd.read_excel("coalpublic2013.xlsx",sheet_name = 'coalpublic2013')
coalPublicData.head()

**Q122.** Write a pandas program to import three datasheets from a given excel data (employee.xlsx ) into a single data frame and export the result into new Excel file. <br>
**Note:** Structure of three datasheets are same.

In [ ]:
empDict = pd.ExcelFile("employee.xlsx") # empData is a dictionary
sheetNames = empDict.sheet_names   # get the sheet names

empDataFrame = []
for sheetname in sheetNames:
    sheetData = pd.read_excel(empDict, sheet_name = sheetname)
    sheetData["SheetName"] = sheetname
    empDataFrame.append(sheetData)
    

empDataFrameF = pd.concat(empDataFrame)
empDataFrameF.tail()

**Q123.** Write a pandas program to create the Pivot table with multiple indexes from the data set of the titanic.csv.

In [ ]:
titanicData = pd.read_csv("titanic.csv")
titanicData.head()

In [ ]:
titanicData.drop([titanicData.columns[15]], axis = 'columns',inplace = True)

In [ ]:
len(titanicData.columns)

**Pivot Table:**  It is a summary of your data, packaged in a chart that lets you report on and explore trends based on your info.

pivot_table requires a data and an index parameter
index is the feature that allows you to group your data. 

In [ ]:
# 'Sex' is used as the index
pivotTable = pd.pivot_table(data=titanicData, index=['sex'])
pivotTable

**Q124.** Write a Pandas program to create the Pivot table and find survival rate by gender?

In [ ]:
# 'sex' is used as the index
pivotTable = pd.pivot_table(data=titanicData, index=['sex'])
print("survival_Rate by gender\n", pivotTable["survived"])

**Q125.** Write a pandas program to make partition each of the passengers into 4 categories based on their age. <br>
**Note:** Age categories- (0, 10), (10, 30), (30, 60), (60, 80)

In [ ]:
bins = [0,10,30,60,80] 
names = ["0-10","10-30","30-60","60-80"]
titanicData["AgeCategory"]=pd.cut(titanicData["age"], bins,labels = names)
titanicData.head()

In [ ]:
print(titanicData.dtypes)

**Q126.** Write a pandas program to create the Pivot table and find survival rate by the gender, age of the different categories of various classes.

In [ ]:
pivotTable1 = pd.pivot_table(data=titanicData, index=['sex','AgeCategory'])
print("survival_Rate by gender\n", pivotTable1["survived"])

**Q127.** Write a pandas program to create the Pivot table and calculate number of women and men were in a particular cabin class.

In [ ]:
pivotTable2 = titanicData.pivot_table(index=['sex'],columns = ["pclass"], aggfunc="count")
pivotTable2
# print("survival_Rate by gender\n", pivotTable1["survived"])


In [ ]:
pivotTable2 = titanicData[["sex","pclass","who"]].pivot_table(index=['sex'],columns =["pclass"], aggfunc="count")
pivotTable2
# print("survival_Rate by gender\n", pivotTable1["survived"])

**Q128.** Write a pandas program to create the Pivot table and separate the gender according to whether they travelled alone or not, to get the probability of survival.

In [ ]:
pivotTable3 = titanicData.pivot_table("survived", index=['sex', 'alone'],columns = 'pclass',aggfunc="count")
pivotTable3


In [ ]:
Analysis: 
1. female survived who travelled alone in pclass 1 = 34
2. 

**Q129.** Write a pandas program to create the Pivot table and find the probability of survival by class, gender, solo boarding, and the port of embarkation.

In [ ]:
pivotTable4 = titanicData.pivot_table("survived",index=['pclass','sex'],columns=["alone","embarked"])
pivotTable4

In [ ]:
# import Ufo DataSet
ufoDataFrame = pd.read_csv("ufo1.csv", parse_dates = ["Date_time", 'date_documented'])

In [ ]:
ufoDataFrame.columns

In [ ]:
ufoDataFrame.tail()

In [ ]:
ufoDataFrame.info()

**Q130.** Write a pandas program to get current date, oldest date and number of days between Current date and the oldest date of Ufo dataset.

In [ ]:
import datetime as dt
from datetime import date

# get current date
# today = dt.datetime.today().strftime('%m-%d-%Y') 
today = date.today()

print("Current Date-->",today)

# oldest date in ufo Dataset
date_sorted = ufoDataFrame.sort_values("Date_time")
old_date = date_sorted["Date_time"].head(1).dt.date
print("Oldest date of Ufo Dataset-->", old_date.to_string(index = False))

# number of days between current date and oldest date of UFO Dataset
num_days = (today - old_date)
print("number of days = ", num_days.to_string(index = False))

# number of weeks between current date and oldest date
num_weeks =num_days/np.timedelta64(1,'W')
print("number of weeks = ", num_weeks.to_string(index = False))

# number of months between current date and oldest date
num_months =num_days/np.timedelta64(1,'M')
print("number of months = ", num_months.to_string(index = False))

**Q131.** Write a pandas program to get all sighting days of the unidentified flying object (ufo) between 1950-10-10 and 1960-10-10.

In [ ]:
sighting_days = ufoDataFrame[(ufoDataFrame['Date_time']>='1950-10-10 00:00:00') & (ufoDataFrame['Date_time']<= '1960-10-10 23:59:59')]
print("all sighting days of the Ufo between 1950-10-10 and 1960-10-10-->\n", sighting_days)

**Q132.** Write a Pandas program to extract the year, month, day, hour, minute, second, and weekday from unidentified flying object (UFO) reporting date.

In [ ]:
ufo_reporting_date = ufoDataFrame["Date_time"].iloc[1]

print(ufo_reporting_date)

# extract the year

print("Year-->",ufo_reporting_date.year)

# extract the month
print("month-->",ufo_reporting_date.month)

# extract the day
print("day-->",ufo_reporting_date.day)

# extract the hour
print("hour-->",ufo_reporting_date.hour)

# extract the minute
print("minute-->",ufo_reporting_date.minute)

# extract the second
print("seconds-->",ufo_reporting_date.second)

# extract the weekday
print("weekday-->", ufo_reporting_date.day_name())

**Q133.** Write a pandas program to count year-country wise frequency of reporting dates of the unidentified flying object(UFO).

In [ ]:
# make a new column year in dataframe
ufoDataFrame["year"] = ufoDataFrame["Date_time"].apply(lambda x: str(x.year))

ufoDF = ufoDataFrame.groupby(["state/province","year"]).size()  # size() function is used to get an 
                                                        #int representing the number of elements
                                                        #in this object.
print("count year-country wise frequency of reporting dates of the unidentified flying object(UFO) \n", ufoDF )

**Q134.** Write a pandas program to get the difference (in days) between documented date and reporting date of unidentified flying object (UFO).

In [ ]:
reporting_date = ufoDataFrame["Date_time"].dt.date
date_documented = ufoDataFrame["date_documented"].dt.date
num_days = (date_documented-reporting_date)
print("\nDifference (in days) between documented date and reporting date of UFO:")
print(num_days)

# type(ufoDataFrame["date_documented"].iloc[0])
# type(reporting_date.iloc[1])

# reporting_date.head()

**Q135.** Write a pandas program to generate sequences of fixedfrequency dates and time spans.

In [ ]:
dt_frame = pd.date_range('2018-01-01', periods=8, freq='H')  #  after every hour
dt_frame

**Q136.** Write a pandas program to manipulate and convert date times with timezone information.

In [ ]:
dt_frame = dt_frame.tz_convert('UTC')
print("UTC time zone",dt_frame)


**Q137.** Write a pandas program to create the graphical analysis of UFO (unidentified flying object) Sightings year.

In [ ]:
# number of ufo sightings per year

ufoDF1 = ufoDataFrame.groupby(["year"]).count()  
ufoDF1["Date_time"].head() 

fig = plt.figure(figsize = (25,10))
# ax = fig.add_axes([0,0,1,1])
# ax.bar(languages,popularity, alpha = 0.9, color = 'b')


ufoDF1["Date_time"].plot(kind = 'bar', color = 'r')
plt.title("UFO Sighting per year")
plt.xlabel("Year")
plt.ylabel("Number of sightings")
plt.show()


**Q138.** Write a pandas program to create a comparison of the top 10 years in which the (UFO) was sighted VS each Month.

In [ ]:
# comparision of top 10 years in which UFO was sighted vs each month

**Q139.** Write a pandas program to create a heatmap (rectangular data as a colour-encoded matrix) for comparison of top 10 years in which (UFO ) was sighted VS each Month.

**Q140.** Write a pandas program to create a Timewheel of Hour VS Year comparison of the top 10 years in which the (UFO) was sighted.

**Q141.** Write a python program to draw the line using given axis values with the suitable label in the x-axis, y-axis, and a title. <br>
The code snippet gives the output shown in the screenshot:
![alt text](Img1.jpg)

**Q142.** Write a python program to draw the line charts of the financial data of the Alphabet Inc., between October. 3, 2016 to October 7 2016. <br>
Sample Financial data (fdata.csv)- <br>
Date,Open,High,Low,Close <br>
10-03-16,774.25,776.065002,769.5,772.559998 <br>
10-04-16 , 776.030029, 778.710022,772.890015,776.429993 <br>
10-05-16 , 779.309998, 782.070007,775.650024,776.469971 <br>
10-06-16 , 779 , 780.47998,775.539978,776.859985 <br>
10-07-16,779.659973, 779.659973 , 770.75 , 775.080017 <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img2.jpg)

In [ ]:
# step1: Creating "fdata.csv" file
sampleArray = np.array([['10-03-16', 774.25, 776.065002, 769.5, 772.559998],
                        ['10-04-16', 776.030029, 778.710022, 772.890015, 776.429993],
                        ['10-05-16', 779.309998, 782.070007, 775.650024, 776.469971],
                        ['10-06-16', 779 , 780.47998, 775.539978, 776.859985],
                        ['10-07-16', 779.659973, 779.659973, 770.75, 775.080017]])
sampleDataFrame = pd.DataFrame(sampleArray, columns = ['Date','Open','High','Low','Close'])
sampleDataFrame.to_csv(r'fdata.csv', index = False)

# step2: Reading "fdata.csv"
fdata = pd.read_csv("fdata.csv")
fdata.head()


Step 3: `line charts` of the financial data of the `Alphabet Inc.`, between October. 3, 2016 to October 7 2016.

In [ ]:
import matplotlib.pyplot as plt

# gca stands for 'get current axis'
ax = plt.gca()

fdata.plot(kind='line',x='Date',y= ['Open','High','Low','Close'],ax=ax)
# df.plot(kind='line',x='name',y='num_pets', color='red', ax=ax)

plt.show()

##### Plotly is built on top of d3.js and is specifically a charting library which can be used directly with Pandas dataframes, thanks to another library named `Cufflinks` .

In [ ]:
#importing plotly and cufflinks in offline mode
import cufflinks as cf
import plotly.offline
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

fdata.iplot(kind="scatter", theme="white",x="Date",y=['Open','High','Low','Close'],xTitle='Date',yTitle='Financial Data')

# fdata["Date"].iplot(kind="scatter", theme="white", title="Passenger's Ages",xTitle='Ages', yTitle='Open')

**Q143.** Write a Python program to plot two or more lines on same plot with the suitable legends of each line. <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img3.jpg)

**Q144.** Write a python programming to display a bar chart of the popularity of programming languages. <br>
Sample data: <br>
programming languages- Java, Python, PHP, JavaScript, C#, C++ <br>
Popularity- 22.2, 17.6, 8.8, 8, 7.7 , 6.7 <br>
The code snippet gives the output shown in the screenshot: ![alt text](Img4.jpg)

In [ ]:
languages = np.array(['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++'])
popularity = np.array([22.2, 17.6, 8.8, 8, 7.7 , 6.7])

fig = plt.figure(figsize = (5,3))
ax = fig.add_axes([0,0,1,1])
ax.bar(languages,popularity, alpha = 0.9, color = 'b')

plt.minorticks_on()
# plt.grid(which='major', linestyle='-', linewidth='0.5', color = 'red')
plt.grid(which='minor', linestyle=':', linewidth='0.5')

plt.xlabel('Programming Languages')
plt.ylabel('Popularity')
plt.title('Programming language popularity')

plt.show()

**Q145.** Write a python programming to display a horizontal bar chart of the popularity of programming languages. <br>
Sample data: <br>
programming languages- Java, Python, PHP, JavaScript, C#, C++ <br>
Popularity- 22.2, 17.6, 8.8, 8, 7.7 , 6.7

In [ ]:
languages = np.array(['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++'])
popularity = np.array([22.2, 17.6, 8.8, 8, 7.7 , 6.7])

fig = plt.figure(figsize = (5,3))
ax = fig.add_axes([0,0,1,1])
ax.barh(languages,popularity, alpha = 0.8, color = 'g')

plt.minorticks_on()
plt.grid(which='major', linestyle='-', linewidth='0.5', color = 'red')
plt.grid(which='minor', linestyle=':', linewidth='0.5')

plt.xlabel('Programming Languages')
plt.ylabel('Popularity')
plt.title('Programming language popularity')

plt.show()

**Q146.** Write a python programming to display a bar chart of the Popularity of programming languages. Increase bottom margin. <br>
Sample data: <br>
programming languages: Java, Python, PHP, JavaScript, C#, C++ <br>
Popularity: 22.2, 17.6, 8.8, 8, 7.7 , 6.7 

In [ ]:
languages = np.array(['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++'])
popularity = np.array([22.2, 17.6, 8.8, 8, 7.7 , 6.7])

fig = plt.figure(figsize = (5,3))
ax = fig.add_axes([0,0,1,1])
ax.bar(languages,popularity, alpha = 0.5, color = 'b')

plt.minorticks_on()
plt.grid(which='major', linestyle='-', linewidth='0.5', color = 'red')
plt.grid(which='minor', linestyle=':', linewidth='0.5')

plt.xlabel('Programming Languages')
plt.ylabel('Popularity')
plt.title('Programming language popularity')

plt.show()

**Q147.** Write a python program to create the bar plot from a DataFrame. <br>
a b c d e <br>
2 4,8,5,7,6 <br>
4 2,3,4,2,6 <br>
6 4,7,4,7, 8 <br>
8 2,6,4,8, 6 <br>
10 2,4,3,3, 2 <br>

In [ ]:
arr1 = np.array([[4,8,5,7,6],
                 [2,3,4,2,6],
                 [4,7,4,7,8],
                 [2,6,4,8,6],
                 [2,4,3,3,2]])
data = pd.DataFrame(arr1, columns = ['a','b','c','d','e'], index = [2,4,6,8,10])

data.plot(kind = 'bar')

plt.minorticks_on()
plt.grid(which='major', linestyle='-', linewidth='0.5')
plt.grid(which='minor', linestyle=':', linewidth='0.5')
plt.show()


**Q148.** Write a python program to draw the scatter plot comparing two subject marks of Mathematics and Science. Use marks of 10 students. <br>
Sample data: <br>
Test Datamath_marks = [88, 92 , 80, 89, 100, 80, 60, 100, 80, 34] <br>
science_marks = [35, 79, 79 , 48, 100, 88, 32, 45, 20, 30] <br>
marks_range = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [ ]:
plt.style.use('classic')

math_marks = [88, 92 , 80, 89, 100, 80, 60, 100, 80, 34]
science_marks = [35, 79, 79 , 48, 100, 88, 32, 45, 20, 30]
marks_range = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

plt.scatter(marks_range, math_marks,c = 'r', label = 'Maths Marks')
plt.scatter(marks_range, science_marks, c = 'b',label = 'Science Marks')

plt.xlabel('Marks Range', fontsize=16)
plt.ylabel('Marks Scored', fontsize=16)
plt.title('scatter plot',fontsize=20)
plt.legend(loc = 'upper right')
plt.show()


**Q149.** Write a python program to draw the scatter plot for three different groups comparing weights and heights. 

In [ ]:
weight1 = np.array([[67,57.2,59.6,59.64,55.8,61.2,60.45,61,56.23,56]])
height1 = [101.7,197.6,98.3,125.1,113.7,157.7,136,148.9,125.3,114.9] 
weight2 = np.array([[61.9,64,62.1,64.2,62.3,65.4,62.4,61.4,62.5,63.6]])
height2 = [152.8,155.3,135.1,125.2,151.3,135,182.2,195.9,165.1,125.1] 
weight3 = np.array([[68.2,67.2,68.4,68.7,71,71.3,70.8,70,71.1,71.7]])
height3 = [165.8,170.9,192.8,135.4,161.4,136.1,167.1,235.1,181.1,177.3]

fig, ax = plt.subplots()
ax.scatter(weight1, height1, c = 'b')
ax.scatter(weight2, height2, c = 'g')
ax.scatter(weight3, height3, c = 'r')

plt.xlabel('weight', fontsize=16)
plt.ylabel('height', fontsize=16)
plt.title('scatter plot - height vs weight',fontsize=20)
# plt.show()

**Q150.** Write a python program to draw a scatter plot to find sea-level rise in past 100 years.

[https://github.com/datasets/sea-level-rise].
This data contains "cumulative changes in sea level for the world’s oceans since 1880, based on a combination of long-term tide gauge measurements and recent satellite measurements. It shows average absolute sea level change, which refers to the height of the ocean surface, regardless of whether nearby land is rising or falling. Satellite data are based solely on measured sea level, while the long-term tide gauge data include a small correction factor because the size and shape of the oceans are changing slowly over time. (On average, the ocean floor has been gradually sinking since the last Ice Age peak, 20,000 years ago.)"

In [ ]:
sea_level = pd.read_csv("sealevel.csv")
sea_level.dropna(how = "all").to_csv("sea_level1.csv")

In [ ]:
sea_level = pd.read_csv("sea_level1.csv")
sea_level.drop(columns = ["Unnamed: 0"], axis = 1, inplace = True)
sea_level.head()

In [ ]:
plt.scatter(sea_level['Year'], sea_level['CSIRO Adjusted Sea Level'],edgecolors='r', alpha=0.5)
plt.xlabel('Year')
plt.ylabel('Sea Level (inches)')
plt.title('Rise in Sea level')
plt.show()